import type { ScopePreset } from "../types";

export const BOT_SEO_SCOPE_V1: ScopePreset = {
  presetId: "BOT_SEO_SCOPE_V1",
  presetName: "BOT Consulting — Scope Completion Preset (v2.1 Data Integrity Verified)",
  version: "2.1.0",
  targetClient: "BOT Consulting",
  description:
    "Accurately defines the BOT Consulting working agreement by isolating Core Basic SEO deliverables from Included Quick Technical items, Complimentary Advanced improvements, and decoupled Advanced Recommendations.",
  items: [
    // =========================================================================
    // TIER A: CORE_COMMITTED_BASIC (Core Contractual Basic SEO Scope)
    // =========================================================================
    {
      id: "CORE_MISSING_H1",
      title: "Primary <h1> Heading on All Pages",
      description: "Ensure every indexable page has a single descriptive visible <h1> heading defining its core topic.",
      tier: "CORE_COMMITTED_BASIC",
      mappedRuleCodes: ["CONTENT_MISSING_H1"],
      mappingType: "FULL",
      evaluation: "AUTOMATIC",
      requiredForCompletion: true,
      weight: 1.0,
      notes: "Fully machine verifiable. CMS collection templates resolve multiple pages with 1 change.",
    },
    {
      id: "CORE_MULTIPLE_H1",
      title: "Single <h1> Tag per Document",
      description: "Eliminate multiple conflicting <h1> headings on single documents, converting extra headings to <h2>.",
      tier: "CORE_COMMITTED_BASIC",
      mappedRuleCodes: ["CONTENT_MULTIPLE_H1"],
      mappingType: "FULL",
      evaluation: "AUTOMATIC",
      requiredForCompletion: true,
      weight: 1.0,
    },
    {
      id: "CORE_HEADING_HIERARCHY",
      title: "Heading Hierarchy & Structure",
      description: "Ensure heading tags follow semantic descending order without skipping levels (e.g. H2 directly to H4) and have non-empty text.",
      tier: "CORE_COMMITTED_BASIC",
      mappedRuleCodes: ["CONTENT_SKIPPED_HEADINGS", "CONTENT_EMPTY_HEADING"],
      mappingType: "FULL",
      evaluation: "AUTOMATIC",
      requiredForCompletion: true,
      weight: 1.0,
    },
    {
      id: "CORE_IMAGE_ALT",
      title: "Image ALT Attributes on Informative Images",
      description: "Ensure meaningful/informative images have descriptive alt text and decorative images use alt=''.",
      tier: "CORE_COMMITTED_BASIC",
      mappedRuleCodes: ["ASSET_MISSING_ALT", "IMAGE_LINK_MISSING_ALT"],
      mappingType: "FULL",
      evaluation: "HYBRID",
      requiredForCompletion: true,
      weight: 1.0,
      notes: "Technical missing alt is machine-detected; distinguishing decorative vs informative requires editorial confirmation.",
    },
    {
      id: "CORE_BROKEN_INTERNAL_LINKS",
      title: "Zero Broken Internal Links (4xx/5xx)",
      description: "Identify and repair any broken internal anchor links pointing to non-existent or erroring internal pages (including specific AR.BOT marketplace references).",
      tier: "CORE_COMMITTED_BASIC",
      mappedRuleCodes: ["LINKS_BROKEN_INTERNAL"],
      mappingType: "FULL",
      evaluation: "AUTOMATIC",
      requiredForCompletion: true,
      weight: 1.0,
    },
    {
      id: "CORE_URL_STRUCTURE_REVIEW",
      title: "SEO-Friendly URL Structure / Friendly Links Review",
      description: "Review URL path structures and slugs. Existing live URLs must NOT be modified merely for cosmetic reasons without a mandatory 301 migration plan.",
      tier: "CORE_COMMITTED_BASIC",
      mappedRuleCodes: [],
      mappingType: "PARTIAL",
      evaluation: "HYBRID",
      requiredForCompletion: true,
      weight: 1.0,
      manualChecklistId: "MANUAL_URL_SLUG_REVIEW",
      notes: "Evaluates URL parameters, path nesting, and live URL migration risk. Does not rely on anchor hash checks.",
    },
    {
      id: "CORE_VISIBLE_COPY_QA",
      title: "Minor Visible Content & Copy Layout QA",
      description: "Editorial review of visible page content for obvious copy, typographical, or visual layout defects.",
      tier: "CORE_COMMITTED_BASIC",
      mappedRuleCodes: [],
      mappingType: "DETECTION_GAP",
      evaluation: "MANUAL",
      requiredForCompletion: true,
      weight: 1.0,
      manualChecklistId: "MANUAL_CONTENT_COPY_QA",
      detectionGap: {
        gapId: "GAP_VISIBLE_COPY_QA",
        requirementTitle: "Minor Visible Content & Copy QA",
        scopeTier: "CORE_COMMITTED_BASIC",
        currentCapability: "MANUAL_QA",
        reasonIncomplete: "Crawler evaluates DOM and HTML semantics, not visual layout alignment or brand copy style rules.",
        importanceToCommitment: "HIGH",
        recommendedAction: "KEEP_MANUAL",
      },
    },
    {
      id: "CORE_HEADING_CAPS",
      title: "Heading Capitalization Consistency",
      description: "Ensure headings across primary landing pages adhere to consistent title casing / sentence casing.",
      tier: "CORE_COMMITTED_BASIC",
      mappedRuleCodes: [],
      mappingType: "DETECTION_GAP",
      evaluation: "MANUAL",
      requiredForCompletion: true,
      weight: 1.0,
      manualChecklistId: "MANUAL_HEADING_CAPS",
      detectionGap: {
        gapId: "GAP_HEADING_CAPS",
        requirementTitle: "Heading Capitalization Consistency",
        scopeTier: "CORE_COMMITTED_BASIC",
        currentCapability: "MANUAL_QA",
        reasonIncomplete: "Requires brand editorial style guide rules (AP Title Case vs Chicago vs Sentence case).",
        importanceToCommitment: "MEDIUM",
        recommendedAction: "KEEP_MANUAL",
      },
    },
    {
      id: "CORE_DUPLICATE_VISIBLE_TEXT",
      title: "Minor Duplicated Visible Copy QA",
      description: "Identify and resolve visible repeated text snippets and boilerplate copy on key service landing pages.",
      tier: "CORE_COMMITTED_BASIC",
      mappedRuleCodes: [],
      mappingType: "DETECTION_GAP",
      evaluation: "MANUAL",
      requiredForCompletion: true,
      weight: 1.0,
      manualChecklistId: "MANUAL_DUP_VISIBLE_TEXT",
      detectionGap: {
        gapId: "GAP_VISIBLE_DUP_TEXT",
        requirementTitle: "Minor Duplicated Visible Copy QA",
        scopeTier: "CORE_COMMITTED_BASIC",
        currentCapability: "MANUAL_QA",
        reasonIncomplete: "Current duplicate rules evaluate exact and near Jaccard similarity sitewide; visible paragraph repetition requires editorial review.",
        importanceToCommitment: "MEDIUM",
        recommendedAction: "KEEP_MANUAL",
      },
    },

    // =========================================================================
    // TIER B: INCLUDED_QUICK_TECHNICAL (Straightforward Technical Extras)
    // =========================================================================
    {
      id: "TECH_MAIN_LANDMARK",
      title: "Semantic <main> Landmark Structure",
      description: "Ensure each HTML document has a semantic <main> element enclosing primary unique content.",
      tier: "INCLUDED_QUICK_TECHNICAL",
      mappedRuleCodes: ["A11Y_MISSING_MAIN_LANDMARK"],
      mappingType: "FULL",
      evaluation: "AUTOMATIC",
      requiredForCompletion: true,
      weight: 1.0,
    },
    {
      id: "TECH_ACCESSIBLE_FORM_LABELS",
      title: "Accessible Form Control Labels",
      description: "Ensure form inputs, textareas, and search fields have associated <label> or aria-label attributes.",
      tier: "INCLUDED_QUICK_TECHNICAL",
      mappedRuleCodes: ["A11Y_UNLABELLED_FORM_CONTROL"],
      mappingType: "FULL",
      evaluation: "AUTOMATIC",
      requiredForCompletion: true,
      weight: 1.0,
    },
    {
      id: "TECH_ACCESSIBLE_LINK_NAMES",
      title: "Accessible Anchor Text & Link Labels",
      description: "Eliminate empty anchor tags and generic non-descriptive link text (e.g. 'click here', 'read more').",
      tier: "INCLUDED_QUICK_TECHNICAL",
      mappedRuleCodes: ["LINKS_EMPTY_ANCHOR", "LINKS_NON_DESCRIPTIVE_ANCHOR"],
      mappingType: "FULL",
      evaluation: "AUTOMATIC",
      requiredForCompletion: true,
      weight: 1.0,
    },
    {
      id: "TECH_IMAGE_DIMENSIONS",
      title: "Image Intrinsic Dimensions (CLS Prevention)",
      description: "Provide width and height attributes on images to prevent Cumulative Layout Shift during loading.",
      tier: "INCLUDED_QUICK_TECHNICAL",
      mappedRuleCodes: ["ASSET_MISSING_DIMENSIONS"],
      mappingType: "FULL",
      evaluation: "AUTOMATIC",
      requiredForCompletion: true,
      weight: 1.0,
    },
    {
      id: "TECH_PRECONNECT_CLEANUP",
      title: "Resource Preconnect Link Tag Optimization",
      description: "Ensure preconnect link tags in <head> point only to active external CDN domains (e.g. fonts.googleapis.com).",
      tier: "INCLUDED_QUICK_TECHNICAL",
      mappedRuleCodes: [],
      mappingType: "DETECTION_GAP",
      evaluation: "MANUAL",
      requiredForCompletion: false,
      weight: 1.0,
      manualChecklistId: "MANUAL_PRECONNECT",
      detectionGap: {
        gapId: "GAP_PRECONNECT_CLEANUP",
        requirementTitle: "Resource Preconnect Link Tag Cleanup",
        scopeTier: "INCLUDED_QUICK_TECHNICAL",
        currentCapability: "CURRENT_DETECTION_GAP",
        reasonIncomplete: "Crawler audits HTML head tags but does not currently maintain an active socket preconnect validator.",
        importanceToCommitment: "LOW",
        recommendedAction: "ADD_SMALL_RULE_LATER",
      },
    },
    {
      id: "TECH_FONT_DISPLAY",
      title: "Font Display CSS Configuration (font-display: swap)",
      description: "Ensure custom web fonts use font-display: swap in CSS to eliminate Flash of Invisible Text (FOIT).",
      tier: "INCLUDED_QUICK_TECHNICAL",
      mappedRuleCodes: [],
      mappingType: "DETECTION_GAP",
      evaluation: "MANUAL",
      requiredForCompletion: false,
      weight: 1.0,
      manualChecklistId: "MANUAL_FONT_DISPLAY",
      detectionGap: {
        gapId: "GAP_FONT_DISPLAY",
        requirementTitle: "font-display: swap Configuration",
        scopeTier: "INCLUDED_QUICK_TECHNICAL",
        currentCapability: "CURRENT_DETECTION_GAP",
        reasonIncomplete: "External Webflow stylesheet font-face rules require stylesheet CSS parser to verify font-display value.",
        importanceToCommitment: "LOW",
        recommendedAction: "ADD_SMALL_RULE_LATER",
      },
    },
    {
      id: "TECH_IFRAME_TITLE",
      title: "Iframe Descriptive Title Attributes",
      description: "Ensure embedded iframes (e.g. HubSpot forms, Google Maps, YouTube) have accessible title attributes.",
      tier: "INCLUDED_QUICK_TECHNICAL",
      mappedRuleCodes: [],
      mappingType: "DETECTION_GAP",
      evaluation: "MANUAL",
      requiredForCompletion: true,
      weight: 1.0,
      manualChecklistId: "MANUAL_IFRAME_TITLE",
      detectionGap: {
        gapId: "GAP_IFRAME_TITLE",
        requirementTitle: "Iframe Title Attribute Verification",
        scopeTier: "INCLUDED_QUICK_TECHNICAL",
        currentCapability: "CURRENT_DETECTION_GAP",
        reasonIncomplete: "Production asset rules audit <img> and <script> tags; iframe attribute checks require dedicated DOM selector.",
        importanceToCommitment: "MEDIUM",
        recommendedAction: "ADD_SMALL_RULE_LATER",
      },
    },
    {
      id: "TECH_IFRAME_LAZY",
      title: "Iframe Native Lazy Loading (loading='lazy')",
      description: "Ensure embedded iframes below the fold utilize native loading='lazy' attribute.",
      tier: "INCLUDED_QUICK_TECHNICAL",
      mappedRuleCodes: [],
      mappingType: "DETECTION_GAP",
      evaluation: "MANUAL",
      requiredForCompletion: true,
      weight: 1.0,
      manualChecklistId: "MANUAL_IFRAME_LAZY",
      detectionGap: {
        gapId: "GAP_IFRAME_LAZY",
        requirementTitle: "Iframe Lazy Loading Verification",
        scopeTier: "INCLUDED_QUICK_TECHNICAL",
        currentCapability: "CURRENT_DETECTION_GAP",
        reasonIncomplete: "Requires iframe element inspection during HTML extraction.",
        importanceToCommitment: "LOW",
        recommendedAction: "ADD_SMALL_RULE_LATER",
      },
    },
    {
      id: "TECH_CSS_CONTRAST",
      title: "Minor CSS & Color Contrast Hygiene",
      description: "Review button and text color contrast for obvious readability defects.",
      tier: "INCLUDED_QUICK_TECHNICAL",
      mappedRuleCodes: [],
      mappingType: "DETECTION_GAP",
      evaluation: "MANUAL",
      requiredForCompletion: false,
      weight: 1.0,
      manualChecklistId: "MANUAL_CSS_CONTRAST",
      detectionGap: {
        gapId: "GAP_CSS_CONTRAST",
        requirementTitle: "Minor CSS & Color Contrast Hygiene",
        scopeTier: "INCLUDED_QUICK_TECHNICAL",
        currentCapability: "MANUAL_QA",
        reasonIncomplete: "Requires computed style evaluation across multiple viewport sizes.",
        importanceToCommitment: "LOW",
        recommendedAction: "NOT_WORTH_AUTOMATING",
      },
    },

    // =========================================================================
    // TIER C: COMPLIMENTARY_ADVANCED (High-Value Advanced Quick Improvements)
    // =========================================================================
    {
      id: "ADV_DUPLICATE_TITLES",
      title: "Duplicate Page Titles Resolution",
      description: "Resolve identical <title> tags shared across distinct URLs to ensure unique SERP snippets.",
      tier: "COMPLIMENTARY_ADVANCED",
      mappedRuleCodes: ["DUP_IDENTICAL_TITLE"],
      mappingType: "FULL",
      evaluation: "AUTOMATIC",
      requiredForCompletion: false,
      weight: 1.0,
    },
    {
      id: "ADV_MISSING_META_DESC",
      title: "Missing Meta Descriptions",
      description: "Add descriptive meta descriptions to pages lacking snippet copy.",
      tier: "COMPLIMENTARY_ADVANCED",
      mappedRuleCodes: ["CONTENT_MISSING_META_DESC"],
      mappingType: "FULL",
      evaluation: "AUTOMATIC",
      requiredForCompletion: false,
      weight: 1.0,
    },
    {
      id: "ADV_DUPLICATE_META_DESC",
      title: "Duplicate Meta Descriptions",
      description: "Differentiate meta descriptions shared across multiple URLs.",
      tier: "COMPLIMENTARY_ADVANCED",
      mappedRuleCodes: ["DUP_META_DESC"],
      mappingType: "FULL",
      evaluation: "AUTOMATIC",
      requiredForCompletion: false,
      weight: 1.0,
    },
    {
      id: "ADV_DUPLICATE_H1",
      title: "Duplicate Primary <h1> Headings Across Pages",
      description: "Ensure distinct pages have distinct primary headings.",
      tier: "COMPLIMENTARY_ADVANCED",
      mappedRuleCodes: ["DUP_H1"],
      mappingType: "FULL",
      evaluation: "AUTOMATIC",
      requiredForCompletion: false,
      weight: 1.0,
    },
    {
      id: "ADV_ORPHAN_PAGES",
      title: "Orphan Indexable Pages Integration",
      description: "Link unlinked indexable pages into site navigation or XML sitemaps.",
      tier: "COMPLIMENTARY_ADVANCED",
      mappedRuleCodes: ["ORPHAN_INDEXABLE_PAGE"],
      mappingType: "FULL",
      evaluation: "AUTOMATIC",
      requiredForCompletion: false,
      weight: 1.0,
    },
    {
      id: "ADV_LINKS_TO_REDIRECT",
      title: "Internal Links Through 3xx Redirects",
      description: "Update internal links pointing to redirecting URLs to target direct 200 OK endpoints.",
      tier: "COMPLIMENTARY_ADVANCED",
      mappedRuleCodes: ["LINKS_INTERNAL_TO_REDIRECT"],
      mappingType: "FULL",
      evaluation: "AUTOMATIC",
      requiredForCompletion: false,
      weight: 1.0,
    },
    {
      id: "ADV_REDIRECT_CLEANUP",
      title: "Redirect Chain & Loop Resolution",
      description: "Consolidate multi-hop redirect chains into single direct hops.",
      tier: "COMPLIMENTARY_ADVANCED",
      mappedRuleCodes: ["REDIRECT_CHAIN"],
      mappingType: "FULL",
      evaluation: "AUTOMATIC",
      requiredForCompletion: false,
      weight: 1.0,
    },
    {
      id: "ADV_CANONICAL_DEFECTS",
      title: "Simple Canonical Destination Fixes",
      description: "Ensure canonical tags do not point to 4xx errors or redirecting URLs.",
      tier: "COMPLIMENTARY_ADVANCED",
      mappedRuleCodes: ["CANONICAL_POINTS_TO_4XX", "CANONICAL_POINTS_TO_REDIRECT"],
      mappingType: "FULL",
      evaluation: "AUTOMATIC",
      requiredForCompletion: false,
      weight: 1.0,
    },
    {
      id: "ADV_MALFORMED_JSON_LD",
      title: "Malformed Structured Data Syntax Repair",
      description: "Fix syntax errors in JSON-LD scripts to allow Google rich snippet parsing.",
      tier: "COMPLIMENTARY_ADVANCED",
      mappedRuleCodes: ["SCHEMA_MALFORMED_JSON"],
      mappingType: "FULL",
      evaluation: "AUTOMATIC",
      requiredForCompletion: false,
      weight: 1.0,
    },
    {
      id: "ADV_SOCIAL_OG_TAGS",
      title: "OpenGraph Social Metadata Completeness",
      description: "Add og:title, og:description, and og:image tags for rich social sharing cards.",
      tier: "COMPLIMENTARY_ADVANCED",
      mappedRuleCodes: ["SOCIAL_INCOMPLETE_OG"],
      mappingType: "FULL",
      evaluation: "AUTOMATIC",
      requiredForCompletion: false,
      weight: 1.0,
    },
    {
      id: "ADV_SNIPPET_LENGTH",
      title: "Title and Meta Description Length Optimization",
      description: "Optimize title tags (30–60 chars) and meta descriptions (70–160 chars) for SERP display.",
      tier: "COMPLIMENTARY_ADVANCED",
      mappedRuleCodes: [
        "TITLE_TOO_SHORT",
        "TITLE_TOO_LONG",
        "META_DESC_TOO_SHORT",
        "META_DESC_TOO_LONG",
      ],
      mappingType: "FULL",
      evaluation: "AUTOMATIC",
      requiredForCompletion: false,
      weight: 1.0,
    },
    {
      id: "ADV_PLACEHOLDER_ANCHORS",
      title: "Placeholder Interactive Control Cleanup (href='#')",
      description: "Convert non-link interactive triggers (href='#') to native button elements or real URLs.",
      tier: "COMPLIMENTARY_ADVANCED",
      mappedRuleCodes: ["CODE_PLACEHOLDER_ANCHOR"],
      mappingType: "FULL",
      evaluation: "AUTOMATIC",
      requiredForCompletion: false,
      weight: 1.0,
    },
    {
      id: "ADV_RESOURCE_CLEANUP",
      title: "Broken Script, Stylesheet & Mixed Content Hygiene",
      description: "Fix broken CSS/JS resources and replace insecure HTTP asset requests.",
      tier: "COMPLIMENTARY_ADVANCED",
      mappedRuleCodes: [
        "SEC_MIXED_CONTENT",
        "RESOURCE_BROKEN_SCRIPT",
        "RESOURCE_BROKEN_STYLESHEET",
      ],
      mappingType: "FULL",
      evaluation: "AUTOMATIC",
      requiredForCompletion: false,
      weight: 1.0,
    },
    {
      id: "ADV_SITEMAP_INDEXABILITY",
      title: "Sitemap Indexability Consistency",
      description: "Ensure XML sitemap contains only indexable 200 OK URLs (no 4xx, redirects, or noindex).",
      tier: "COMPLIMENTARY_ADVANCED",
      mappedRuleCodes: [
        "SITEMAP_URL_4XX",
        "SITEMAP_URL_REDIRECT",
        "SITEMAP_URL_NOINDEX",
      ],
      mappingType: "FULL",
      evaluation: "AUTOMATIC",
      requiredForCompletion: false,
      weight: 1.0,
    },

    // =========================================================================
    // TIER D: ADVANCED_RECOMMENDATION (Strategic Scope - NEVER reduces completion)
    // =========================================================================
    {
      id: "REC_CONTENT_EXPANSION",
      title: "Substantial Content Expansion & Intent Enrichment",
      description: "Strategic content enhancement for low-word-count or thin pages.",
      tier: "ADVANCED_RECOMMENDATION",
      mappedRuleCodes: ["CONTENT_THIN_WORD_COUNT"],
      mappingType: "FULL",
      evaluation: "HYBRID",
      requiredForCompletion: false,
    },
    {
      id: "REC_NEAR_DUPLICATE_CONSOLIDATION",
      title: "Near-Duplicate Content Strategy & URL Consolidation",
      description: "Evaluate highly similar pages for canonicalization, consolidation, or differentiation.",
      tier: "ADVANCED_RECOMMENDATION",
      mappedRuleCodes: ["DUP_MAIN_CONTENT_NEAR", "DUP_MAIN_CONTENT_EXACT"],
      mappingType: "FULL",
      evaluation: "HYBRID",
      requiredForCompletion: false,
    },
    {
      id: "REC_SOFT_404_EVALUATION",
      title: "Soft 404 Candidate Editorial Review",
      description: "Review pages with thin text and error-like phrasing to return true 404 or enrich content.",
      tier: "ADVANCED_RECOMMENDATION",
      mappedRuleCodes: ["SOFT_404_CANDIDATE"],
      mappingType: "FULL",
      evaluation: "HYBRID",
      requiredForCompletion: false,
    },
    {
      id: "REC_SERVER_SECURITY_HYGIENE",
      title: "Server Security Header Configuration (nosniff)",
      description: "Configure reverse proxy / CDN headers for X-Content-Type-Options: nosniff.",
      tier: "ADVANCED_RECOMMENDATION",
      mappedRuleCodes: ["SEC_MISSING_NOSNIFF"],
      mappingType: "FULL",
      evaluation: "AUTOMATIC",
      requiredForCompletion: false,
    },
    {
      id: "REC_DEEP_CRAWL_DEPTH",
      title: "Information Architecture & Deep Crawl Depth Restructuring",
      description: "Flatten site hierarchy so important indexable pages are reachable within 3 clicks.",
      tier: "ADVANCED_RECOMMENDATION",
      mappedRuleCodes: ["PAGES_DEEP_CRAWL_DEPTH"],
      mappingType: "FULL",
      evaluation: "AUTOMATIC",
      requiredForCompletion: false,
    },
    {
      id: "REC_PERFORMANCE_OPTIMIZATION",
      title: "Core Web Vitals & Server TTFB Optimization",
      description: "Optimize large HTML payloads and server response latencies.",
      tier: "ADVANCED_RECOMMENDATION",
      mappedRuleCodes: ["PERF_LARGE_HTML_PAYLOAD", "PERF_SLOW_SERVER_RESPONSE"],
      mappingType: "FULL",
      evaluation: "AUTOMATIC",
      requiredForCompletion: false,
    },
    {
      id: "REC_INTERNATIONAL_HREFLANG",
      title: "Internationalization & Hreflang Architecture",
      description: "Configure multi-lingual annotations and bidirectional return links.",
      tier: "ADVANCED_RECOMMENDATION",
      mappedRuleCodes: [
        "HREFLANG_INVALID_CODE",
        "HREFLANG_MISSING_RETURN",
        "HREFLANG_SELF_REF_MISSING",
      ],
      mappingType: "FULL",
      evaluation: "AUTOMATIC",
      requiredForCompletion: false,
    },
    {
      id: "REC_STRUCTURED_DATA_EXPANSION",
      title: "Advanced Schema.org Entity Architecture",
      description: "Add domain-specific rich schema types (Organization, JobPosting, Service, Article).",
      tier: "ADVANCED_RECOMMENDATION",
      mappedRuleCodes: ["SCHEMA_MISSING_TYPE", "SCHEMA_INVALID_CONTEXT"],
      mappingType: "FULL",
      evaluation: "HYBRID",
      requiredForCompletion: false,
    },
    {
      id: "REC_CRITICAL_INDEXABILITY_SAFEGUARDS",
      title: "Severe Indexability, Canonical & Crawl Policy Safeguards",
      description: "Monitor and enforce severe crawl/index safeguards (noindex, redirect loops, robots conflicts, sitemap orphans).",
      tier: "ADVANCED_RECOMMENDATION",
      mappedRuleCodes: [
        "INDEX_NOINDEX",
        "INDEX_ROBOTS_CONFLICT",
        "INDEX_MISSING_CANONICAL",
        "CANONICAL_POINTS_TO_NOINDEX",
        "CANONICAL_MULTIPLE",
        "CANONICAL_OUTSIDE_HEAD",
        "REDIRECT_LOOP",
        "IMAGE_BROKEN",
        "MOBILE_VIEWPORT_MISSING",
        "MOBILE_VIEWPORT_INVALID",
        "HTML_TITLE_MULTIPLE",
        "HTML_META_DESC_MULTIPLE",
        "INDEX_SITEMAP_ORPHAN",
        "SITEMAP_MALFORMED_XML",
        "LINKS_BROKEN_EXTERNAL",
      ],
      mappingType: "FULL",
      evaluation: "AUTOMATIC",
      requiredForCompletion: false,
    },
  ],
};
