/**
 * Suspicious Link Pattern Engine & Disavow Safety Boundary.
 * Detects observable anomalous link patterns (repetitive exact anchors across unrelated domains,
 * autogenerated URL patterns) without manufacturing toxic-score heuristics or automated disavows.
 */

import { BacklinkRecord, SuspiciousLinkPatternReview } from "./types";
import { DEFAULT_BACKLINK_POLICY, BacklinkIntelligencePolicy } from "./config";

export function detectSuspiciousLinkPatterns(
  backlinks: BacklinkRecord[],
  policy: BacklinkIntelligencePolicy = DEFAULT_BACKLINK_POLICY
): SuspiciousLinkPatternReview[] {
  const reviews: SuspiciousLinkPatternReview[] = [];

  // 1. Check for Large Burst of Identical Commercial Anchors Across Multiple Unrelated Domains
  const anchorDomainMap = new Map<string, Set<string>>();
  for (const bl of backlinks) {
    if (bl.anchorClassification === "EXACT_MATCH_CANDIDATE" && bl.anchorText.trim().length > 3) {
      const anchorNorm = bl.anchorText.trim().toLowerCase();
      const domains = anchorDomainMap.get(anchorNorm) || new Set<string>();
      domains.add(bl.sourceRegistrableDomain);
      anchorDomainMap.set(anchorNorm, domains);
    }
  }

  for (const [anchor, domainSet] of anchorDomainMap.entries()) {
    if (domainSet.size >= policy.suspiciousAnchorDomainThreshold) {
      const matchingBacklinks = backlinks.filter((b) => b.anchorText.trim().toLowerCase() === anchor);
      reviews.push({
        patternId: `SUSP_BURST_ANCHOR_${Math.abs(hashString(anchor))}`,
        patternType: "LARGE_BURST_IDENTICAL_ANCHORS",
        affectedDomainCount: domainSet.size,
        affectedBacklinkCount: matchingBacklinks.length,
        sampleSourceDomains: Array.from(domainSet).slice(0, 5),
        sampleAnchors: [anchor],
        confidence: "MEDIUM_CONFIDENCE",
        interpretationNote: `Identical commercial anchor '${anchor}' observed across ${domainSet.size} distinct referring domains. Review for potential coordinated link schemes or syndication patterns. (Descriptive observation; no automated penalty or disavow implied).`,
        isAutomatedDisavow: false,
      });
    }
  }

  // 2. Check for High Sitewide Template Repetition from Unrelated Domains
  const sitewideDomains = new Set<string>();
  const domainBacklinkCount = new Map<string, number>();
  for (const bl of backlinks) {
    const count = (domainBacklinkCount.get(bl.sourceRegistrableDomain) || 0) + 1;
    domainBacklinkCount.set(bl.sourceRegistrableDomain, count);
    if (count >= policy.sitewideRepetitionThreshold) {
      sitewideDomains.add(bl.sourceRegistrableDomain);
    }
  }

  if (sitewideDomains.size >= 5) {
    const totalSitewideLinks = backlinks.filter((b) => sitewideDomains.has(b.sourceRegistrableDomain)).length;
    reviews.push({
      patternId: "SUSP_SITEWIDE_TEMPLATES",
      patternType: "HIGH_SITEWIDE_TEMPLATE_REPETITION",
      affectedDomainCount: sitewideDomains.size,
      affectedBacklinkCount: totalSitewideLinks,
      sampleSourceDomains: Array.from(sitewideDomains).slice(0, 5),
      sampleAnchors: Array.from(
        new Set(backlinks.filter((b) => sitewideDomains.has(b.sourceRegistrableDomain)).map((b) => b.anchorText))
      ).slice(0, 5),
      confidence: "LOW_CONFIDENCE",
      interpretationNote: `${sitewideDomains.size} referring domains contain repetitive sitewide links totaling ${totalSitewideLinks} backlink records. Review template placement context.`,
      isAutomatedDisavow: false,
    });
  }

  return reviews;
}

function hashString(str: string): number {
  let hash = 0;
  for (let i = 0; i < str.length; i++) {
    hash = (hash << 5) - hash + str.charCodeAt(i);
    hash |= 0;
  }
  return hash;
}
