import * as fs from "fs";
import * as path from "path";
import { IMPLEMENTED_DIAGNOSTIC_RULES } from "./rule-inventory";

export interface CoverageAreaAudit {
  area: string;
  category: string;
  capability: string;
  currentRules: string[];
  coverage: "FULL" | "PARTIAL" | "NONE" | "NOT_APPLICABLE";
  confidence: "CONFIRMED" | "HIGH_CONFIDENCE" | "HEURISTIC" | "MANUAL_REVIEW";
  missing: boolean;
  value: "CRITICAL" | "HIGH" | "MEDIUM" | "LOW";
  feasibility: "HIGH" | "MEDIUM" | "LOW";
  recommendation: "ADD_NOW" | "ADD_LATER" | "EXTERNAL_DATA_REQUIRED" | "MANUAL_ONLY" | "NOT_WORTH_ADDING" | "NOT_APPLICABLE";
  rationale: string;
}

export interface CandidateGap {
  candidateRuleCode: string;
  category: string;
  title: string;
  priority: "P0" | "P1" | "P2" | "P3";
  problem: string;
  whyValuable: string;
  existingCoverage: string;
  whyInsufficient: string;
  requiredEvidence: string;
  falsePositiveRisk: string;
  proposedSeverity: "critical" | "warning" | "opportunity" | "notice";
  proposedConfidence: "confirmed" | "likely" | "heuristic" | "manual_review";
  isScoring: boolean;
  basePenalty: number;
  fixIntelligenceFamily: string;
  fixtureStrategy: string;
}

export const COVERAGE_AREAS_MATRIX: CoverageAreaAudit[] = [
  // A. Advanced Indexability & Canonicalization
  {
    area: "Advanced Indexability",
    category: "indexability",
    capability: "Canonical points to 4xx error or redirect",
    currentRules: ["CANONICAL_POINTS_TO_4XX", "CANONICAL_POINTS_TO_REDIRECT"],
    coverage: "FULL",
    confidence: "CONFIRMED",
    missing: false,
    value: "CRITICAL",
    feasibility: "HIGH",
    recommendation: "NOT_APPLICABLE",
    rationale: "Fully covered by existing production rules.",
  },
  {
    area: "Advanced Indexability",
    category: "indexability",
    capability: "Canonical chain / loop resolution (Canonical A -> B -> C)",
    currentRules: [],
    coverage: "NONE",
    confidence: "CONFIRMED",
    missing: true,
    value: "CRITICAL",
    feasibility: "HIGH",
    recommendation: "ADD_NOW",
    rationale: "Search engines ignore chained canonicals or choose unexpected canonicals. Must be detected deterministically.",
  },
  {
    area: "Advanced Indexability",
    category: "indexability",
    capability: "Relative canonical URL tag syntax (<link rel='canonical' href='/path'>)",
    currentRules: [],
    coverage: "NONE",
    confidence: "CONFIRMED",
    missing: true,
    value: "HIGH",
    feasibility: "HIGH",
    recommendation: "ADD_NOW",
    rationale: "RFC and search engines require absolute canonical URLs to prevent protocol/base-href ambiguity.",
  },
  {
    area: "Advanced Indexability",
    category: "indexability",
    capability: "HTTP X-Robots-Tag vs HTML Meta Robots conflict",
    currentRules: [],
    coverage: "NONE",
    confidence: "CONFIRMED",
    missing: true,
    value: "CRITICAL",
    feasibility: "HIGH",
    recommendation: "ADD_NOW",
    rationale: "Contradictory directives (e.g. HTTP header noindex vs HTML meta index) cause severe indexing confusion.",
  },
  {
    area: "Advanced Indexability",
    category: "indexability",
    capability: "Internal links pointing to noindex pages",
    currentRules: [],
    coverage: "NONE",
    confidence: "CONFIRMED",
    missing: true,
    value: "HIGH",
    feasibility: "HIGH",
    recommendation: "ADD_NOW",
    rationale: "Internal links waste crawl equity and create mixed signals when targeting noindex destinations.",
  },

  // B. Robots.txt Advanced Validation
  {
    area: "Robots.txt Validation",
    category: "indexability",
    capability: "Robots.txt disallows critical CSS/JS rendering resources",
    currentRules: [],
    coverage: "NONE",
    confidence: "CONFIRMED",
    missing: true,
    value: "CRITICAL",
    feasibility: "HIGH",
    recommendation: "ADD_NOW",
    rationale: "Googlebot requires CSS/JS access to render mobile layouts and execute client-side components.",
  },
  {
    area: "Robots.txt Validation",
    category: "indexability",
    capability: "Robots.txt missing Sitemap reference",
    currentRules: [],
    coverage: "NONE",
    confidence: "CONFIRMED",
    missing: true,
    value: "MEDIUM",
    feasibility: "HIGH",
    recommendation: "ADD_NOW",
    rationale: "Robots.txt should declare Sitemap location for rapid crawler discovery.",
  },

  // C. Sitemap Advanced Validation
  {
    area: "Sitemap Validation",
    category: "sitemaps",
    capability: "Sitemap contains 4xx, redirect, or noindex URLs",
    currentRules: ["SITEMAP_URL_4XX", "SITEMAP_URL_REDIRECT", "SITEMAP_URL_NOINDEX"],
    coverage: "FULL",
    confidence: "CONFIRMED",
    missing: false,
    value: "HIGH",
    feasibility: "HIGH",
    recommendation: "NOT_APPLICABLE",
    rationale: "Fully covered in existing production inventory.",
  },
  {
    area: "Sitemap Validation",
    category: "sitemaps",
    capability: "Sitemap URL blocked by robots.txt",
    currentRules: [],
    coverage: "NONE",
    confidence: "CONFIRMED",
    missing: true,
    value: "CRITICAL",
    feasibility: "HIGH",
    recommendation: "ADD_NOW",
    rationale: "Submitting a URL in sitemap while disallowing it in robots.txt is a direct contradictory directive.",
  },
  {
    area: "Sitemap Validation",
    category: "sitemaps",
    capability: "Sitemap contains non-self-canonical URL (URL canonicalizes elsewhere)",
    currentRules: [],
    coverage: "NONE",
    confidence: "CONFIRMED",
    missing: true,
    value: "HIGH",
    feasibility: "HIGH",
    recommendation: "ADD_NOW",
    rationale: "XML sitemaps must only contain authoritative self-canonical URLs.",
  },
  {
    area: "Sitemap Validation",
    category: "sitemaps",
    capability: "Duplicate URL entries in XML sitemap",
    currentRules: [],
    coverage: "NONE",
    confidence: "CONFIRMED",
    missing: true,
    value: "MEDIUM",
    feasibility: "HIGH",
    recommendation: "ADD_NOW",
    rationale: "Redundant entries inflate sitemap file size and waste parser processing.",
  },

  // D. URL Normalization & Duplicate States
  {
    area: "URL Architecture",
    category: "url_architecture",
    capability: "Internal links use non-normalized URL variants (casing/trailing slashes/index.html)",
    currentRules: [],
    coverage: "NONE",
    confidence: "CONFIRMED",
    missing: true,
    value: "HIGH",
    feasibility: "HIGH",
    recommendation: "ADD_NOW",
    rationale: "Linking inconsistently to /about/ vs /about or /About creates duplicate URL discovery and link equity dilution.",
  },
  {
    area: "URL Architecture",
    category: "url_architecture",
    capability: "Internal links contain session IDs or tracking parameters",
    currentRules: [],
    coverage: "NONE",
    confidence: "CONFIRMED",
    missing: true,
    value: "HIGH",
    feasibility: "HIGH",
    recommendation: "ADD_NOW",
    rationale: "Session IDs (e.g. jsessionid) and internal UTM tags create infinite crawl spider traps.",
  },

  // E. Redirect Advanced Coverage
  {
    area: "Redirects",
    category: "redirects",
    capability: "Redirect chains and redirect loops",
    currentRules: ["REDIRECT_CHAIN", "REDIRECT_LOOP"],
    coverage: "FULL",
    confidence: "CONFIRMED",
    missing: false,
    value: "CRITICAL",
    feasibility: "HIGH",
    recommendation: "NOT_APPLICABLE",
    rationale: "Fully covered in existing production inventory.",
  },
  {
    area: "Redirects",
    category: "redirects",
    capability: "Redirect destination resolves to 4xx/5xx broken error",
    currentRules: [],
    coverage: "NONE",
    confidence: "CONFIRMED",
    missing: true,
    value: "CRITICAL",
    feasibility: "HIGH",
    recommendation: "ADD_NOW",
    rationale: "A 301/302 that redirects into a 404 or 500 error causes severe dead-end crawl traps.",
  },
  {
    area: "Redirects",
    category: "redirects",
    capability: "HTML Meta Refresh redirect tag detected",
    currentRules: [],
    coverage: "NONE",
    confidence: "CONFIRMED",
    missing: true,
    value: "HIGH",
    feasibility: "HIGH",
    recommendation: "ADD_NOW",
    rationale: "<meta http-equiv='refresh'> is slow, poorly indexed, and should be replaced by server-side 301.",
  },

  // F. HTTP & Server Technical SEO
  {
    area: "HTTP Technical",
    category: "code_validation",
    capability: "HTTP 5xx Server Error on crawled page",
    currentRules: [],
    coverage: "NONE",
    confidence: "CONFIRMED",
    missing: true,
    value: "CRITICAL",
    feasibility: "HIGH",
    recommendation: "ADD_NOW",
    rationale: "Server 5xx errors stop Googlebot crawling and cause de-indexing if persistent.",
  },
  {
    area: "HTTP Technical",
    category: "code_validation",
    capability: "HTML document served with incorrect MIME type",
    currentRules: [],
    coverage: "NONE",
    confidence: "CONFIRMED",
    missing: true,
    value: "HIGH",
    feasibility: "HIGH",
    recommendation: "ADD_NOW",
    rationale: "Pages served as text/plain or application/octet-stream fail standard HTML DOM parser rendering in search engines.",
  },

  // G. JavaScript & Rendering SEO
  {
    area: "Rendering SEO",
    category: "indexability",
    capability: "Critical metadata (Title / Canonical / Robots) altered by client-side JavaScript",
    currentRules: [],
    coverage: "NONE",
    confidence: "CONFIRMED",
    missing: true,
    value: "CRITICAL",
    feasibility: "HIGH",
    recommendation: "ADD_NOW",
    rationale: "Search engines reading raw HTML index initial metadata; discrepancy with rendered JS creates indexing volatility.",
  },

  // H. Structured Data Technical Validation
  {
    area: "Structured Data",
    category: "social_schema",
    capability: "Malformed JSON-LD syntax, missing @type, invalid context",
    currentRules: ["SCHEMA_MALFORMED_JSON", "SCHEMA_MISSING_TYPE", "SCHEMA_INVALID_CONTEXT"],
    coverage: "FULL",
    confidence: "CONFIRMED",
    missing: false,
    value: "HIGH",
    feasibility: "HIGH",
    recommendation: "NOT_APPLICABLE",
    rationale: "Syntax, missing type, and context are covered.",
  },
  {
    area: "Structured Data",
    category: "social_schema",
    capability: "Malformed BreadcrumbList structure / missing position index",
    currentRules: [],
    coverage: "NONE",
    confidence: "CONFIRMED",
    missing: true,
    value: "HIGH",
    feasibility: "HIGH",
    recommendation: "ADD_NOW",
    rationale: "Breadcrumb schema is essential for Google search rich snippets; invalid position breaks rich results.",
  },
  {
    area: "Structured Data",
    category: "social_schema",
    capability: "Invalid ISO 8601 date format in datePublished / dateModified",
    currentRules: [],
    coverage: "NONE",
    confidence: "CONFIRMED",
    missing: true,
    value: "MEDIUM",
    feasibility: "HIGH",
    recommendation: "ADD_NOW",
    rationale: "Non-standard date formats fail Article rich results validation.",
  },

  // I. International SEO
  {
    area: "International SEO",
    category: "international_seo",
    capability: "Invalid language/region code, missing return reciprocal, self-ref missing",
    currentRules: ["HREFLANG_INVALID_CODE", "HREFLANG_MISSING_RETURN", "HREFLANG_SELF_REF_MISSING"],
    coverage: "FULL",
    confidence: "CONFIRMED",
    missing: false,
    value: "HIGH",
    feasibility: "HIGH",
    recommendation: "NOT_APPLICABLE",
    rationale: "Core hreflang syntax and reciprocity covered.",
  },
  {
    area: "International SEO",
    category: "international_seo",
    capability: "Hreflang points to non-indexable URL (4xx, redirect, or noindex)",
    currentRules: [],
    coverage: "NONE",
    confidence: "CONFIRMED",
    missing: true,
    value: "CRITICAL",
    feasibility: "HIGH",
    recommendation: "ADD_NOW",
    rationale: "Hreflang annotations pointing to broken or redirecting URLs are rejected by Google.",
  },
  {
    area: "International SEO",
    category: "international_seo",
    capability: "Multi-language site missing x-default annotation",
    currentRules: [],
    coverage: "NONE",
    confidence: "HIGH_CONFIDENCE",
    missing: true,
    value: "MEDIUM",
    feasibility: "HIGH",
    recommendation: "ADD_NOW",
    rationale: "Sites with 3+ language variations require an x-default fallback for unmatched geographies.",
  },

  // J. Advanced Image / Media SEO
  {
    area: "Image / Media SEO",
    category: "page_speed_assets",
    capability: "Above-the-fold LCP image configured with lazy-loading (loading='lazy')",
    currentRules: [],
    coverage: "NONE",
    confidence: "CONFIRMED",
    missing: true,
    value: "HIGH",
    feasibility: "HIGH",
    recommendation: "ADD_NOW",
    rationale: "Applying loading='lazy' to hero/header images delays LCP rendering by hundreds of milliseconds.",
  },

  // K. Deferred / External / Manual Boundaries
  {
    area: "Search Console Performance",
    category: "search_console",
    capability: "Google search query rankings, impressions, average CTR",
    currentRules: [],
    coverage: "NONE",
    confidence: "CONFIRMED",
    missing: true,
    value: "HIGH",
    feasibility: "LOW",
    recommendation: "EXTERNAL_DATA_REQUIRED",
    rationale: "Phase 8 boundary: requires Google Search Console OAuth integration.",
  },
  {
    area: "Core Web Vitals Field Data",
    category: "performance_crux",
    capability: "CrUX Real User Monitoring (INP, LCP, CLS 75th percentile)",
    currentRules: [],
    coverage: "NONE",
    confidence: "CONFIRMED",
    missing: true,
    value: "HIGH",
    feasibility: "LOW",
    recommendation: "EXTERNAL_DATA_REQUIRED",
    rationale: "Phase 7 boundary: requires PageSpeed Insights / CrUX API integration.",
  },
  {
    area: "Editorial Copy Quality",
    category: "content_relevance",
    capability: "Subjective readability scores, keyword density quotas",
    currentRules: [],
    coverage: "NOT_APPLICABLE",
    confidence: "HEURISTIC",
    missing: false,
    value: "LOW",
    feasibility: "LOW",
    recommendation: "NOT_WORTH_ADDING",
    rationale: "Subjective content metrics generate noisy warnings and do not represent deterministic technical SEO.",
  },
];

export const PHASE_6_CANDIDATE_GAP_PLAN: CandidateGap[] = [
  // 1. CANONICAL_CHAIN (P0)
  {
    candidateRuleCode: "CANONICAL_CHAIN",
    category: "indexability",
    title: "Canonical chain detected (Canonical points to another canonicalized page)",
    priority: "P0",
    problem: "Page A specifies Page B as canonical, but Page B specifies Page C as canonical.",
    whyValuable: "Search engines ignore multi-hop canonical chains or select arbitrary index targets.",
    existingCoverage: "CANONICAL_POINTS_TO_REDIRECT only detects redirect hops, not canonical-to-canonical hops.",
    whyInsufficient: "Direct canonical chains without HTTP 301 redirects are currently undetectable.",
    requiredEvidence: "Canonical target URL and its resolved canonical destination.",
    falsePositiveRisk: "Zero (pure deterministic graph traversal).",
    proposedSeverity: "critical",
    proposedConfidence: "confirmed",
    isScoring: true,
    basePenalty: 3.0,
    fixIntelligenceFamily: "indexability-canonical-strategy",
    fixtureStrategy: "6 fixtures: Direct A->B->C, Loop A->B->A, Self-canonical TN, No-canonical TN, 3-hop chain, Cross-domain chain.",
  },
  // 2. ROBOTS_HEADER_META_CONFLICT (P0)
  {
    candidateRuleCode: "ROBOTS_HEADER_META_CONFLICT",
    category: "indexability",
    title: "Conflicting indexing directives between HTTP X-Robots-Tag and HTML Meta Robots",
    priority: "P0",
    problem: "HTTP response header specifies 'noindex' while HTML <meta name='robots'> specifies 'index' (or vice-versa).",
    whyValuable: "Contradictory directives create severe indexation ambiguity across crawlers.",
    existingCoverage: "INDEX_NOINDEX and INDEX_ROBOTS_CONFLICT detect single-source directives or robots.txt conflicts.",
    whyInsufficient: "No rule cross-references HTTP headers against HTML meta tags.",
    requiredEvidence: "HTTP header value vs HTML meta content value.",
    falsePositiveRisk: "Zero (pure deterministic header vs DOM comparison).",
    proposedSeverity: "critical",
    proposedConfidence: "confirmed",
    isScoring: true,
    basePenalty: 4.0,
    fixIntelligenceFamily: "indexability-canonical-strategy",
    fixtureStrategy: "6 fixtures: Header noindex + Meta index (TP), Header index + Meta noindex (TP), Agreeing index (TN), Agreeing noindex (TN), Missing header (TN), Missing meta (TN).",
  },
  // 3. SITEMAP_URL_BLOCKED_BY_ROBOTS (P0)
  {
    candidateRuleCode: "SITEMAP_URL_BLOCKED_BY_ROBOTS",
    category: "sitemaps",
    title: "Sitemap contains URL disallowed in robots.txt",
    priority: "P0",
    problem: "A URL submitted in the XML Sitemap is explicitly blocked from crawling by robots.txt.",
    whyValuable: "Direct contradiction between submission intent and crawl instruction wastes search engine processing.",
    existingCoverage: "INDEX_ROBOTS_CONFLICT checks crawled pages; SITEMAP_URL_NOINDEX checks noindex in sitemap.",
    whyInsufficient: "Sitemap URLs that are disallowed in robots.txt without being crawled are currently missed.",
    requiredEvidence: "Sitemap URL and matching robots.txt disallow rule pattern.",
    falsePositiveRisk: "Zero (deterministic robots parser match).",
    proposedSeverity: "critical",
    proposedConfidence: "confirmed",
    isScoring: true,
    basePenalty: 3.0,
    fixIntelligenceFamily: "sitemap-robots-strategy",
    fixtureStrategy: "6 fixtures: Disallowed /admin/ in sitemap (TP), Wildcard disallowed URL (TP), Allowed URL (TN), Clean sitemap (TN), Query param disallow (TP), Commented disallow (TN).",
  },
  // 4. ROBOTS_BLOCKED_IMPORTANT_RESOURCE (P0)
  {
    candidateRuleCode: "ROBOTS_BLOCKED_IMPORTANT_RESOURCE",
    category: "indexability",
    title: "Robots.txt blocks critical CSS or JavaScript rendering resources",
    priority: "P0",
    problem: "Robots.txt disallows crawler access to CSS or JS resources required to render the page.",
    whyValuable: "Googlebot renders pages like a modern browser; blocking CSS/JS causes rendering degradation and mobile indexing penalties.",
    existingCoverage: "RESOURCE_BROKEN_SCRIPT only detects 4xx/5xx HTTP errors.",
    whyInsufficient: "Valid 200 OK scripts that are blocked in robots.txt are not flagged.",
    requiredEvidence: "Script/CSS URL and matching robots.txt disallow rule.",
    falsePositiveRisk: "Zero (strict matching against <link rel='stylesheet'> and <script src>).",
    proposedSeverity: "critical",
    proposedConfidence: "confirmed",
    isScoring: true,
    basePenalty: 3.5,
    fixIntelligenceFamily: "sitemap-robots-strategy",
    fixtureStrategy: "6 fixtures: Disallowed /css/*.css (TP), Disallowed /js/*.js (TP), Disallowed analytics script (TN), Allowed CSS/JS (TN), Allowed inline script (TN), Disallowed media (TN).",
  },
  // 5. REDIRECT_TO_BROKEN_4XX (P0)
  {
    candidateRuleCode: "REDIRECT_TO_BROKEN_4XX",
    category: "redirects",
    title: "Redirect target resolves to broken 4xx or 5xx error",
    priority: "P0",
    problem: "A 301/302 redirect points to a target destination that returns HTTP 4xx or 5xx.",
    whyValuable: "Creates dead-end crawl traps where users and crawlers are redirected into broken pages.",
    existingCoverage: "REDIRECT_CHAIN detects multi-hop redirects; LINKS_BROKEN_INTERNAL detects direct broken links.",
    whyInsufficient: "Redirects originating at server level that terminate in 404 are not flagged under link rules.",
    requiredEvidence: "Initial redirect URL, status code, and final broken status code.",
    falsePositiveRisk: "Zero (deterministic HTTP status chain).",
    proposedSeverity: "critical",
    proposedConfidence: "confirmed",
    isScoring: true,
    basePenalty: 3.5,
    fixIntelligenceFamily: "redirects-strategy",
    fixtureStrategy: "6 fixtures: 301 -> 404 (TP), 302 -> 500 (TP), 301 -> 200 (TN), 301 -> 301 -> 404 (TP), 301 -> 301 -> 200 (TN), Direct 200 (TN).",
  },
  // 6. HTTP_STATUS_5XX_SERVER_ERROR (P0)
  {
    candidateRuleCode: "HTTP_STATUS_5XX_SERVER_ERROR",
    category: "code_validation",
    title: "Server 5xx Internal Error on crawled page",
    priority: "P0",
    problem: "Crawled page returns HTTP 500, 502, 503, or 504 server error.",
    whyValuable: "Server errors prevent indexation and cause rapid SERP de-ranking if unresolved.",
    existingCoverage: "PERF_SLOW_SERVER_RESPONSE detects latency; broken links check 4xx.",
    whyInsufficient: "A 500 Internal Server Error returned directly on an entry page needs dedicated critical classification.",
    requiredEvidence: "HTTP response status code and error header.",
    falsePositiveRisk: "Zero (deterministic status code >= 500).",
    proposedSeverity: "critical",
    proposedConfidence: "confirmed",
    isScoring: true,
    basePenalty: 4.0,
    fixIntelligenceFamily: "server-security-strategy",
    fixtureStrategy: "6 fixtures: 500 Internal Error (TP), 502 Bad Gateway (TP), 503 Service Unavailable (TP), 200 OK (TN), 404 Not Found (TN), 301 Redirect (TN).",
  },
  // 7. RENDER_CRITICAL_METADATA_DISCREPANCY (P0)
  {
    candidateRuleCode: "RENDER_CRITICAL_METADATA_DISCREPANCY",
    category: "indexability",
    title: "Critical indexing metadata differs between raw HTML and JavaScript-rendered DOM",
    priority: "P0",
    problem: "Client-side JavaScript dynamically injects, removes, or changes <title>, canonical, or robots directives after initial load.",
    whyValuable: "Search engine raw-HTML crawlers see different indexing instructions than rendered-DOM engines, causing indexation volatility.",
    existingCoverage: "None (raw vs rendered parity was previously tested for recall, not flagged as diagnostic finding).",
    whyInsufficient: "Client-side JavaScript altering canonical tags or removing noindex must be surfaced as a critical risk.",
    requiredEvidence: "Raw metadata value vs rendered DOM metadata value.",
    falsePositiveRisk: "Low (strict equality check on canonical, title, and robots content).",
    proposedSeverity: "critical",
    proposedConfidence: "confirmed",
    isScoring: true,
    basePenalty: 3.5,
    fixIntelligenceFamily: "indexability-canonical-strategy",
    fixtureStrategy: "6 fixtures: JS changes canonical URL (TP), JS injects title on empty raw HTML (TP), JS removes noindex (TP), Identical raw & rendered (TN), Server-rendered Next.js (TN), Minor text whitespace diff (TN).",
  },
  // 8. HREFLANG_TARGET_NON_INDEXABLE (P0)
  {
    candidateRuleCode: "HREFLANG_TARGET_NON_INDEXABLE",
    category: "international_seo",
    title: "Hreflang alternate points to a non-indexable URL (4xx, redirect, or noindex)",
    priority: "P0",
    problem: "An <link rel='alternate' hreflang='...'> tag references a URL that returns 404, redirects, or has noindex.",
    whyValuable: "Google ignores hreflang annotations that point to non-indexable or redirecting destinations.",
    existingCoverage: "HREFLANG_INVALID_CODE checks language codes; HREFLANG_MISSING_RETURN checks reciprocity.",
    whyInsufficient: "Hreflang pointing to broken or redirecting target is currently undetectable.",
    requiredEvidence: "Hreflang target URL and its resolved status code / indexability flag.",
    falsePositiveRisk: "Zero (deterministic target inspection).",
    proposedSeverity: "critical",
    proposedConfidence: "confirmed",
    isScoring: true,
    basePenalty: 3.0,
    fixIntelligenceFamily: "international-hreflang-strategy",
    fixtureStrategy: "6 fixtures: Hreflang -> 404 (TP), Hreflang -> 301 (TP), Hreflang -> noindex (TP), Hreflang -> 200 indexable (TN), Clean multi-lingual pair (TN), Single language page (TN).",
  },
  // 9. CANONICAL_RELATIVE (P1)
  {
    candidateRuleCode: "CANONICAL_RELATIVE",
    category: "indexability",
    title: "Relative canonical URL tag syntax (<link rel='canonical' href='/path'>)",
    priority: "P1",
    problem: "Canonical link element uses a relative path (e.g. href='/about') instead of a fully-qualified absolute URL (https://domain.com/about).",
    whyValuable: "RFC 5988 and search engines strongly mandate absolute URLs to prevent protocol, port, or base-URL misinterpretation.",
    existingCoverage: "INDEX_MISSING_CANONICAL checks absence; CANONICAL_OUTSIDE_HEAD checks placement.",
    whyInsufficient: "Relative canonical tags are parsed into normalized URLs internally but never flagged as a syntax defect.",
    requiredEvidence: "Raw href attribute string from HTML DOM.",
    falsePositiveRisk: "Zero (deterministic check: does raw href start with http:// or https://).",
    proposedSeverity: "warning",
    proposedConfidence: "confirmed",
    isScoring: true,
    basePenalty: 1.5,
    fixIntelligenceFamily: "indexability-canonical-strategy",
    fixtureStrategy: "6 fixtures: Relative /path (TP), Relative path without slash (TP), Absolute https:// (TN), Absolute http:// (TN), Protocol-relative //domain.com (TP), Missing canonical (TN).",
  },
  // 10. INTERNAL_LINK_TO_NOINDEX (P1)
  {
    candidateRuleCode: "INTERNAL_LINK_TO_NOINDEX",
    category: "links",
    title: "Internal links pointing to noindex pages",
    priority: "P1",
    problem: "Indexable pages contain standard hyperlinks pointing to pages marked with 'noindex'.",
    whyValuable: "Wastes crawl budget and dilutes internal PageRank toward non-indexable utility or staging endpoints.",
    existingCoverage: "LINKS_INTERNAL_TO_REDIRECT only checks 3xx status.",
    whyInsufficient: "Internal links pointing to 200 OK pages with noindex are not flagged.",
    requiredEvidence: "Source page URL, anchor text, and target page noindex status.",
    falsePositiveRisk: "Low (strict check on indexable source pages linking to internal noindex targets).",
    proposedSeverity: "warning",
    proposedConfidence: "confirmed",
    isScoring: true,
    basePenalty: 1.5,
    fixIntelligenceFamily: "links-architecture-strategy",
    fixtureStrategy: "6 fixtures: Link to noindex page (TP), Link to X-Robots noindex (TP), Link to indexable page (TN), External link to noindex (TN), Link to login wall (TP), Anchor link on same page (TN).",
  },
  // 11. SITEMAP_URL_NON_CANONICAL (P1)
  {
    candidateRuleCode: "SITEMAP_URL_NON_CANONICAL",
    category: "sitemaps",
    title: "Sitemap contains non-self-canonical URL (URL canonicalizes elsewhere)",
    priority: "P1",
    problem: "XML Sitemap lists URL A, but URL A declares a canonical tag pointing to URL B.",
    whyValuable: "Sitemaps must contain only authoritative self-canonical URLs; non-canonical URLs in sitemaps send conflicting signals to Google.",
    existingCoverage: "SITEMAP_URL_REDIRECT checks 3xx; SITEMAP_URL_NOINDEX checks noindex.",
    whyInsufficient: "A 200 OK page in sitemap with cross-page canonical tag is currently missed.",
    requiredEvidence: "Sitemap URL and its declared canonical target URL.",
    falsePositiveRisk: "Zero (deterministic comparison of sitemap URL vs page canonical).",
    proposedSeverity: "warning",
    proposedConfidence: "confirmed",
    isScoring: true,
    basePenalty: 2.0,
    fixIntelligenceFamily: "sitemap-robots-strategy",
    fixtureStrategy: "6 fixtures: Sitemap URL canonicalizes to B (TP), Sitemap URL self-canonical (TN), Sitemap URL no canonical (TN), Cross-domain canonical in sitemap (TP), Clean sitemap (TN), 404 in sitemap (TN).",
  },
  // 12. SITEMAP_URL_DUPLICATE (P1)
  {
    candidateRuleCode: "SITEMAP_URL_DUPLICATE",
    category: "sitemaps",
    title: "Duplicate URL entries declared in XML sitemap",
    priority: "P1",
    problem: "The same normalized URL appears more than once in the XML Sitemap.",
    whyValuable: "Redundant entries waste sitemap parsing limits and indicate CMS sitemap generator defects.",
    existingCoverage: "SITEMAP_MALFORMED_XML only checks XML parse failure.",
    whyInsufficient: "Well-formed XML containing duplicate <loc> tags is not flagged.",
    requiredEvidence: "Duplicate URL string and occurrence count in sitemap.",
    falsePositiveRisk: "Zero (deterministic duplicate check).",
    proposedSeverity: "opportunity",
    proposedConfidence: "confirmed",
    isScoring: true,
    basePenalty: 0.5,
    fixIntelligenceFamily: "sitemap-robots-strategy",
    fixtureStrategy: "6 fixtures: Duplicate exact URL (TP), Duplicate trailing slash variant (TP), Unique URLs list (TN), Sitemap index with unique sitemaps (TN), Empty sitemap (TN), Single URL sitemap (TN).",
  },
  // 13. URL_NON_NORMALIZED_INTERNAL_LINK (P1)
  {
    candidateRuleCode: "URL_NON_NORMALIZED_INTERNAL_LINK",
    category: "url_architecture",
    title: "Internal links use non-normalized URL variants (uppercase, trailing slashes, default files)",
    priority: "P1",
    problem: "Internal hyperlinks point to uppercase paths (/About), trailing-slash variants (/page vs /page/), or default filenames (/index.html).",
    whyValuable: "Splits crawl equity, causes unnecessary redirect hops, and triggers duplicate page discovery.",
    existingCoverage: "None (normalizer resolves URLs for the crawler graph, but does not flag the dirty anchor href).",
    whyInsufficient: "Dirty internal links must be flagged so developers can standardize site navigation.",
    requiredEvidence: "Source page, raw href, and standardized normalized URL.",
    falsePositiveRisk: "Low (excludes query params, hashes, external links).",
    proposedSeverity: "warning",
    proposedConfidence: "likely",
    isScoring: true,
    basePenalty: 1.0,
    fixIntelligenceFamily: "url-architecture-strategy",
    fixtureStrategy: "6 fixtures: Link to /About (TP), Link to /index.html (TP), Link to /page//sub (TP), Clean link to /about (TN), Clean link to / (TN), External mixed case link (TN).",
  },
  // 14. REDIRECT_META_REFRESH (P1)
  {
    candidateRuleCode: "REDIRECT_META_REFRESH",
    category: "redirects",
    title: "Client-side HTML Meta Refresh redirect tag detected",
    priority: "P1",
    problem: "Page uses <meta http-equiv='refresh' content='0;url=...'> instead of HTTP 301 redirect.",
    whyValuable: "Meta refresh redirects are slower, delay indexing, and are explicitly discouraged by Google Webmaster guidelines.",
    existingCoverage: "None.",
    whyInsufficient: "Meta refresh tags in raw HTML were previously unparsed.",
    requiredEvidence: "Raw <meta http-equiv='refresh'> element snippet and target URL.",
    falsePositiveRisk: "Zero (deterministic DOM check).",
    proposedSeverity: "warning",
    proposedConfidence: "confirmed",
    isScoring: true,
    basePenalty: 2.0,
    fixIntelligenceFamily: "redirects-strategy",
    fixtureStrategy: "6 fixtures: Meta refresh 0 sec (TP), Meta refresh 5 sec (TP), Standard 301 page (TN), Clean 200 page (TN), Meta viewport (TN), Meta charset (TN).",
  },
  // 15. SCHEMA_BREADCRUMBLIST_INVALID (P1)
  {
    candidateRuleCode: "SCHEMA_BREADCRUMBLIST_INVALID",
    category: "social_schema",
    title: "Malformed BreadcrumbList schema structure or missing item positions",
    priority: "P1",
    problem: "Structured data declares BreadcrumbList, but itemListElement is missing, position is missing, or positions are non-numeric/non-sequential.",
    whyValuable: "BreadcrumbList is a primary Google rich search feature; structural defects invalidate SERP breadcrumbs.",
    existingCoverage: "SCHEMA_MALFORMED_JSON only checks JSON syntax.",
    whyInsufficient: "Valid JSON with invalid Breadcrumb schema hierarchy is not flagged.",
    requiredEvidence: "Schema snippet, missing position or itemListElement structure.",
    falsePositiveRisk: "Zero (deterministic schema tree validation).",
    proposedSeverity: "warning",
    proposedConfidence: "confirmed",
    isScoring: true,
    basePenalty: 1.5,
    fixIntelligenceFamily: "structured-data-social-strategy",
    fixtureStrategy: "6 fixtures: Missing itemListElement (TP), Missing position (TP), Non-sequential position 1->3 (TP), Valid BreadcrumbList (TN), Valid Organization (TN), Non-schema page (TN).",
  },
  // 16. ROBOTS_SITEMAP_MISSING (P1)
  {
    candidateRuleCode: "ROBOTS_SITEMAP_MISSING",
    category: "indexability",
    title: "Robots.txt missing Sitemap reference",
    priority: "P1",
    problem: "Robots.txt does not declare any XML sitemap location using a Sitemap: directive.",
    whyValuable: "Declaring sitemaps in robots.txt speeds up discovery across all web search engine bots.",
    existingCoverage: "INDEX_SITEMAP_ORPHAN checks sitemap page discovery.",
    whyInsufficient: "Missing sitemap declaration in robots.txt root is not flagged.",
    requiredEvidence: "Site origin robots.txt contents.",
    falsePositiveRisk: "Zero (informational best practice).",
    proposedSeverity: "opportunity",
    proposedConfidence: "confirmed",
    isScoring: false,
    basePenalty: 0.0,
    fixIntelligenceFamily: "indexability-robots-strategy",
    fixtureStrategy: "6 fixtures: Missing sitemap in robots.txt (TP), Empty robots.txt (TP), Valid Sitemap directive in robots.txt (TN), Multiple sitemaps declared (TN), Sitemaps in subfolder (TN), Non-homepage route (TN).",
  },
  // 17. IMAGE_ABOVE_FOLD_LAZY_LOADED (P1)
  {
    candidateRuleCode: "IMAGE_ABOVE_FOLD_LAZY_LOADED",
    category: "page_speed_assets",
    title: "Above-the-fold hero or header image configured with loading='lazy'",
    priority: "P1",
    problem: "The primary header logo or first prominent hero image uses loading='lazy', potentially delaying Largest Contentful Paint (LCP).",
    whyValuable: "Google Core Web Vitals guidelines advise against lazy loading above-the-fold LCP candidates.",
    existingCoverage: "ASSET_MISSING_DIMENSIONS checks width/height; IMAGE_BROKEN checks 404.",
    whyInsufficient: "Eager LCP images with lazy-loading attributes are currently not diagnosed.",
    requiredEvidence: "Image DOM element snippet and hero/header placement.",
    falsePositiveRisk: "Low (restricted to first image in <header> or hero section).",
    proposedSeverity: "opportunity",
    proposedConfidence: "heuristic",
    isScoring: false,
    basePenalty: 0.0,
    fixIntelligenceFamily: "assets-images-strategy",
    fixtureStrategy: "6 fixtures: First hero image with loading=lazy (TP), Header logo with loading=lazy (TP), Below-fold image with loading=lazy (TN), Hero image with loading=eager (TN), Hero image without loading attribute (TN), Background CSS image (TN).",
  },
];
