/**
 * Programmatic Rule Inventory for Dream SEO Diagnostic Engine.
 * Formally declares and categorizes every diagnostic rule implemented in `apps/backend/src/crawler/rules.ts`.
 */

export interface DiagnosticRuleMetadata {
  ruleCode: string;
  category: string;
  title: string;
  description: string;
  severity: "critical" | "warning" | "opportunity" | "notice";
  isScoring: boolean;
  basePenalty: number;
  confidenceType: "confirmed" | "likely" | "heuristic" | "manual_review";
  evaluationMode: "deterministic" | "heuristic" | "externally_verified" | "partially_evaluable";
  applicableResourceTypes: string[];
  primaryPageClasses: string[];
  exclusionFilterDescription: string;
  diagnosticImpact: string;
}

export const IMPLEMENTED_DIAGNOSTIC_RULES: DiagnosticRuleMetadata[] = [
  // =========================================================================
  // 1. CONTENT RELEVANCE & ON-PAGE
  // =========================================================================
  {
    ruleCode: "CONTENT_MISSING_TITLE",
    category: "content_relevance",
    title: "Missing <title> tag on indexable page",
    description: "Page lacks a title element, critical for search engine snippets and relevance.",
    severity: "critical",
    isScoring: true,
    basePenalty: 4.0,
    confidenceType: "confirmed",
    evaluationMode: "deterministic",
    applicableResourceTypes: ["html_page"],
    primaryPageClasses: ["all_indexable_content"],
    exclusionFilterDescription: "Excluded on non-indexable, sitemaps, and utility error endpoints.",
    diagnosticImpact: "Critical search snippet failure and ranking penalty.",
  },
  {
    ruleCode: "TITLE_TOO_SHORT",
    category: "content_relevance",
    title: "Title tag is too short (< 10 characters)",
    description: "Very short titles fail to provide sufficient keyword context for search engines and searchers.",
    severity: "opportunity",
    isScoring: true,
    basePenalty: 0.5,
    confidenceType: "heuristic",
    evaluationMode: "deterministic",
    applicableResourceTypes: ["html_page"],
    primaryPageClasses: ["all_indexable_content"],
    exclusionFilterDescription: "Excluded on utility and non-indexable pages.",
    diagnosticImpact: "Sub-optimal CTR in SERPs and thin keyword signal.",
  },
  {
    ruleCode: "TITLE_TOO_LONG",
    category: "content_relevance",
    title: "Title tag is excessively long (> 70 characters)",
    description: "Titles exceeding ~60-70 characters are truncated by search engines in SERP snippets.",
    severity: "opportunity",
    isScoring: true,
    basePenalty: 0.5,
    confidenceType: "heuristic",
    evaluationMode: "deterministic",
    applicableResourceTypes: ["html_page"],
    primaryPageClasses: ["all_indexable_content"],
    exclusionFilterDescription: "Excluded on utility and non-indexable pages.",
    diagnosticImpact: "Truncated SERP snippet and degraded search visibility.",
  },
  {
    ruleCode: "CONTENT_MISSING_META_DESC",
    category: "content_relevance",
    title: "Missing <meta name='description'> tag",
    description: "Page lacks a meta description for SERP display snippets.",
    severity: "warning",
    isScoring: true,
    basePenalty: 1.5,
    confidenceType: "confirmed",
    evaluationMode: "deterministic",
    applicableResourceTypes: ["html_page"],
    primaryPageClasses: ["all_indexable_content"],
    exclusionFilterDescription: "Excluded on non-indexable and utility endpoints.",
    diagnosticImpact: "Sub-optimal search snippet generation by search engine algorithms.",
  },
  {
    ruleCode: "META_DESC_TOO_SHORT",
    category: "content_relevance",
    title: "Meta description is too short (< 50 characters)",
    description: "Short meta descriptions provide insufficient context in search results to drive click-through rates.",
    severity: "opportunity",
    isScoring: true,
    basePenalty: 0.5,
    confidenceType: "heuristic",
    evaluationMode: "deterministic",
    applicableResourceTypes: ["html_page"],
    primaryPageClasses: ["all_indexable_content"],
    exclusionFilterDescription: "Excluded on non-indexable pages.",
    diagnosticImpact: "Under-utilized snippet real estate in organic search results.",
  },
  {
    ruleCode: "META_DESC_TOO_LONG",
    category: "content_relevance",
    title: "Meta description is excessively long (> 160 characters)",
    description: "Meta descriptions exceeding 160 characters will be truncated with ellipsis in SERP previews.",
    severity: "opportunity",
    isScoring: true,
    basePenalty: 0.5,
    confidenceType: "heuristic",
    evaluationMode: "deterministic",
    applicableResourceTypes: ["html_page"],
    primaryPageClasses: ["all_indexable_content"],
    exclusionFilterDescription: "Excluded on non-indexable pages.",
    diagnosticImpact: "Truncated snippet message in search previews.",
  },
  {
    ruleCode: "CONTENT_MISSING_H1",
    category: "content_relevance",
    title: "Missing primary <h1> heading",
    description: "Page does not contain a primary H1 heading describing the page topic.",
    severity: "critical",
    isScoring: true,
    basePenalty: 4.0,
    confidenceType: "confirmed",
    evaluationMode: "deterministic",
    applicableResourceTypes: ["html_page"],
    primaryPageClasses: ["all_indexable_content"],
    exclusionFilterDescription: "Excluded on utility endpoints and legal/confirmation pages.",
    diagnosticImpact: "Impaired topical hierarchy and search engine topic extraction.",
  },
  {
    ruleCode: "CONTENT_MULTIPLE_H1",
    category: "content_relevance",
    title: "Multiple <h1> headings found",
    description: "Page contains more than one H1 heading element.",
    severity: "warning",
    isScoring: true,
    basePenalty: 1.5,
    confidenceType: "confirmed",
    evaluationMode: "deterministic",
    applicableResourceTypes: ["html_page"],
    primaryPageClasses: ["all_indexable_content"],
    exclusionFilterDescription: "Excluded on utility endpoints.",
    diagnosticImpact: "Dilutes document topic hierarchy signal.",
  },
  {
    ruleCode: "CONTENT_SKIPPED_HEADINGS",
    category: "content_relevance",
    title: "Skipped heading hierarchy levels (e.g. H1 to H3)",
    description: "Heading levels skip numbers (e.g., from H1 directly to H3 or H2 to H4).",
    severity: "opportunity",
    isScoring: true,
    basePenalty: 0.5,
    confidenceType: "confirmed",
    evaluationMode: "deterministic",
    applicableResourceTypes: ["html_page"],
    primaryPageClasses: ["all_indexable_content"],
    exclusionFilterDescription: "Excluded on non-indexable or non-HTML resources.",
    diagnosticImpact: "Accessibility screen reader confusion and irregular document structure.",
  },
  {
    ruleCode: "CONTENT_EMPTY_HEADING",
    category: "content_relevance",
    title: "Empty heading tag (<h1-6></h1-6>)",
    description: "Heading tag contains no visible text or accessible content.",
    severity: "opportunity",
    isScoring: true,
    basePenalty: 0.5,
    confidenceType: "confirmed",
    evaluationMode: "deterministic",
    applicableResourceTypes: ["html_page"],
    primaryPageClasses: ["all_indexable_content"],
    exclusionFilterDescription: "Excluded on non-HTML resources.",
    diagnosticImpact: "Empty DOM nodes in accessibility tree.",
  },
  {
    ruleCode: "CONTENT_THIN_WORD_COUNT",
    category: "content_relevance",
    title: "Thin main content word count (< 180 words)",
    description: "Primary editorial content has fewer than 180 words on eligible content pages.",
    severity: "warning",
    isScoring: true,
    basePenalty: 1.5,
    confidenceType: "likely",
    evaluationMode: "heuristic",
    applicableResourceTypes: ["html_page"],
    primaryPageClasses: ["homepage", "marketing_landing", "article_blog", "active_job", "product_job_detail", "category_listing"],
    exclusionFilterDescription: "Strictly excluded on form_application, search_filter, thank_you_confirmation, utility_legal, and non-indexable pages.",
    diagnosticImpact: "Low content depth trigger for search engine thin content penalties.",
  },
  {
    ruleCode: "SOFT_404_CANDIDATE",
    category: "content_relevance",
    title: "Soft 404 candidate (HTTP 200 with Not Found template)",
    description: "Server returns HTTP 200 OK for a page that displays a missing content or 404 error template.",
    severity: "warning",
    isScoring: false,
    basePenalty: 0.0,
    confidenceType: "manual_review",
    evaluationMode: "heuristic",
    applicableResourceTypes: ["html_page"],
    primaryPageClasses: ["all_html_pages"],
    exclusionFilterDescription: "Surfaced for manual review without deterministic score penalty.",
    diagnosticImpact: "Wasted crawl budget and indexing of useless thin error pages.",
  },

  // =========================================================================
  // 2. DUPLICATE CONTENT
  // =========================================================================
  {
    ruleCode: "DUP_IDENTICAL_TITLE",
    category: "duplicate_content",
    title: "Identical <title> tag shared across multiple distinct pages",
    description: "Two or more distinct URLs share exactly the same title tag.",
    severity: "warning",
    isScoring: true,
    basePenalty: 1.5,
    confidenceType: "confirmed",
    evaluationMode: "deterministic",
    applicableResourceTypes: ["html_page"],
    primaryPageClasses: ["all_indexable_content"],
    exclusionFilterDescription: "Excluded on canonicalized duplicate variants.",
    diagnosticImpact: "Internal keyword cannibalization and index confusion.",
  },
  {
    ruleCode: "DUP_META_DESC",
    category: "duplicate_content",
    title: "Duplicate meta descriptions across indexable pages",
    description: "Multiple distinct pages share identical meta descriptions, reducing SERP snippet distinctiveness.",
    severity: "warning",
    isScoring: true,
    basePenalty: 1.5,
    confidenceType: "confirmed",
    evaluationMode: "deterministic",
    applicableResourceTypes: ["html_page"],
    primaryPageClasses: ["all_indexable_content"],
    exclusionFilterDescription: "Requires exact string match across distinct indexable URLs.",
    diagnosticImpact: "Reduced search snippet differentiation across site landing pages.",
  },
  {
    ruleCode: "DUP_H1",
    category: "duplicate_content",
    title: "Duplicate primary <h1> headings across pages",
    description: "Multiple distinct content pages use the exact same primary H1 heading topic.",
    severity: "opportunity",
    isScoring: true,
    basePenalty: 0.5,
    confidenceType: "confirmed",
    evaluationMode: "deterministic",
    applicableResourceTypes: ["html_page"],
    primaryPageClasses: ["all_indexable_content"],
    exclusionFilterDescription: "Excluded on non-indexable and utility pages.",
    diagnosticImpact: "Topical confusion and internal cannibalization.",
  },
  {
    ruleCode: "DUP_MAIN_CONTENT_EXACT",
    category: "duplicate_content",
    title: "Exact duplicate main content text across multiple URLs",
    description: "Search engines filter out duplicate content, splitting link equity and creating ranking confusion.",
    severity: "warning",
    isScoring: true,
    basePenalty: 3.0,
    confidenceType: "confirmed",
    evaluationMode: "deterministic",
    applicableResourceTypes: ["html_page"],
    primaryPageClasses: ["all_indexable_content"],
    exclusionFilterDescription: "Requires exact normalized text match across distinct indexable URLs.",
    diagnosticImpact: "Algorithmic duplicate filtering and equity dissipation.",
  },
  {
    ruleCode: "DUP_MAIN_CONTENT_NEAR",
    category: "duplicate_content",
    title: "Near-duplicate main content detected (similarity >= 85%)",
    description: "Thin boilerplate variants of the same template can trigger search engine algorithmic cannibalization.",
    severity: "warning",
    isScoring: true,
    basePenalty: 1.5,
    confidenceType: "heuristic",
    evaluationMode: "heuristic",
    applicableResourceTypes: ["html_page"],
    primaryPageClasses: ["all_indexable_content"],
    exclusionFilterDescription: "Evaluates Jaccard token similarity >= 85% on substantial text pages.",
    diagnosticImpact: "Search engine algorithmic clustering and cannibalization.",
  },

  // =========================================================================
  // 3. INDEXABILITY & DIRECTIVES
  // =========================================================================
  {
    ruleCode: "INDEX_MISSING_CANONICAL",
    category: "indexability",
    title: "Missing canonical tag on indexable page",
    description: "Indexable page does not declare a self-referencing canonical tag.",
    severity: "warning",
    isScoring: true,
    basePenalty: 1.5,
    confidenceType: "confirmed",
    evaluationMode: "deterministic",
    applicableResourceTypes: ["html_page"],
    primaryPageClasses: ["all_indexable_content"],
    exclusionFilterDescription: "Excluded on noindex or non-HTML resources.",
    diagnosticImpact: "Potential duplicate content indexing under URL parameters.",
  },
  {
    ruleCode: "INDEX_NOINDEX",
    category: "indexability",
    title: "Noindex directive on indexable content page",
    description: "Directs search engines to drop the page from search results completely.",
    severity: "critical",
    isScoring: true,
    basePenalty: 4.0,
    confidenceType: "confirmed",
    evaluationMode: "deterministic",
    applicableResourceTypes: ["html_page"],
    primaryPageClasses: ["homepage", "marketing_landing", "article_blog", "active_job", "product_job_detail", "category_listing"],
    exclusionFilterDescription: "Excluded on intentional noindex utility pages (login, legal, cart).",
    diagnosticImpact: "Total de-indexation of valuable revenue-driving landing pages.",
  },
  {
    ruleCode: "INDEX_ROBOTS_CONFLICT",
    category: "indexability",
    title: "Conflicting robots directives (e.g. meta index vs header noindex)",
    description: "Contradictory directives cause unpredictable crawling and indexation behavior.",
    severity: "warning",
    isScoring: true,
    basePenalty: 2.0,
    confidenceType: "confirmed",
    evaluationMode: "deterministic",
    applicableResourceTypes: ["html_page"],
    primaryPageClasses: ["all_html_pages"],
    exclusionFilterDescription: "Triggers only on conflicting instructions between meta and header.",
    diagnosticImpact: "Unpredictable bot crawling and erratic SERP dropping.",
  },
  {
    ruleCode: "CANONICAL_POINTS_TO_4XX",
    category: "indexability",
    title: "Canonical tag points to a broken 4xx URL",
    description: "Instructs search engines to consolidate ranking equity to a non-existent page.",
    severity: "critical",
    isScoring: true,
    basePenalty: 4.0,
    confidenceType: "confirmed",
    evaluationMode: "deterministic",
    applicableResourceTypes: ["html_page"],
    primaryPageClasses: ["all_html_pages"],
    exclusionFilterDescription: "Requires verified internal 4xx status on canonical destination.",
    diagnosticImpact: "Complete dropping of canonical target and source from search index.",
  },
  {
    ruleCode: "CANONICAL_POINTS_TO_REDIRECT",
    category: "indexability",
    title: "Canonical tag points to a redirect hop",
    description: "Forces search engines through extra redirect hops to resolve the canonical target.",
    severity: "warning",
    isScoring: true,
    basePenalty: 1.5,
    confidenceType: "confirmed",
    evaluationMode: "deterministic",
    applicableResourceTypes: ["html_page"],
    primaryPageClasses: ["all_html_pages"],
    exclusionFilterDescription: "Requires verified 3xx redirect on canonical destination.",
    diagnosticImpact: "Dilutes PageRank consolidation efficiency.",
  },
  {
    ruleCode: "CANONICAL_POINTS_TO_NOINDEX",
    category: "indexability",
    title: "Canonical tag points to a noindexed page",
    description: "Points canonical authority to a page that explicitly forbids search indexing.",
    severity: "critical",
    isScoring: true,
    basePenalty: 3.5,
    confidenceType: "confirmed",
    evaluationMode: "deterministic",
    applicableResourceTypes: ["html_page"],
    primaryPageClasses: ["all_html_pages"],
    exclusionFilterDescription: "Requires target page with confirmed noindex directive.",
    diagnosticImpact: "Search engines ignore both the canonical and the source page.",
  },
  {
    ruleCode: "CANONICAL_MULTIPLE",
    category: "indexability",
    title: "Multiple canonical tags declared on a single page",
    description: "Declaring multiple rel='canonical' tags causes search engines to ignore all canonical directives.",
    severity: "critical",
    isScoring: true,
    basePenalty: 3.0,
    confidenceType: "confirmed",
    evaluationMode: "deterministic",
    applicableResourceTypes: ["html_page"],
    primaryPageClasses: ["all_html_pages"],
    exclusionFilterDescription: "Triggers when 2 or more distinct canonical URLs are declared.",
    diagnosticImpact: "Search engines discard canonical consolidation completely.",
  },
  {
    ruleCode: "CANONICAL_OUTSIDE_HEAD",
    category: "indexability",
    title: "Canonical link tag declared outside <head> (in <body>)",
    description: "HTML specifications require <link rel='canonical'> to reside strictly in <head>.",
    severity: "warning",
    isScoring: true,
    basePenalty: 1.5,
    confidenceType: "confirmed",
    evaluationMode: "deterministic",
    applicableResourceTypes: ["html_page"],
    primaryPageClasses: ["all_html_pages"],
    exclusionFilterDescription: "Triggers when canonical link is positioned in document body.",
    diagnosticImpact: "Ignored by Google and search engine parsers.",
  },
  {
    ruleCode: "INDEX_SITEMAP_ORPHAN",
    category: "indexability",
    title: "Sitemap orphan URLs (in sitemap but not internally linked)",
    description: "URL exists in XML sitemap but receives zero internal inbound links.",
    severity: "opportunity",
    isScoring: true,
    basePenalty: 0.5,
    confidenceType: "confirmed",
    evaluationMode: "deterministic",
    applicableResourceTypes: ["html_page"],
    primaryPageClasses: ["all_html_pages"],
    exclusionFilterDescription: "Requires complete crawl graph traversal.",
    diagnosticImpact: "Weak internal link equity and delayed indexation.",
  },
  {
    ruleCode: "ORPHAN_INDEXABLE_PAGE",
    category: "indexability",
    title: "Indexable orphan page (0 internal inlinks)",
    description: "An indexable page has 0 internal inbound links within the site's architecture.",
    severity: "warning",
    isScoring: true,
    basePenalty: 1.5,
    confidenceType: "confirmed",
    evaluationMode: "deterministic",
    applicableResourceTypes: ["html_page"],
    primaryPageClasses: ["all_indexable_content"],
    exclusionFilterDescription: "Excluded on seed / homepage URL.",
    diagnosticImpact: "Receives no PageRank flow and will suffer delayed crawling and poor ranking.",
  },
  {
    ruleCode: "PAGES_DEEP_CRAWL_DEPTH",
    category: "indexability",
    title: "Page exceeds recommended crawl depth (> 4 clicks from seed)",
    description: "Pages buried deep in site hierarchy receive lower crawl frequency and weaker authority.",
    severity: "opportunity",
    isScoring: true,
    basePenalty: 0.5,
    confidenceType: "confirmed",
    evaluationMode: "deterministic",
    applicableResourceTypes: ["html_page"],
    primaryPageClasses: ["all_html_pages"],
    exclusionFilterDescription: "Triggers on pages with crawl depth >= 5.",
    diagnosticImpact: "Reduced crawl rate and lower ranking equity.",
  },
  {
    ruleCode: "REDIRECT_CHAIN",
    category: "indexability",
    title: "Redirect chain with multiple intermediate hops (>= 2 hops)",
    description: "Redirect chains slow page load, waste crawl budget, and dissipate link equity.",
    severity: "warning",
    isScoring: true,
    basePenalty: 1.5,
    confidenceType: "confirmed",
    evaluationMode: "deterministic",
    applicableResourceTypes: ["html_page"],
    primaryPageClasses: ["all_html_pages"],
    exclusionFilterDescription: "Triggers when 2 or more intermediate redirect hops occur.",
    diagnosticImpact: "Slows page rendering and increases TTFB for visitors and bots.",
  },
  {
    ruleCode: "REDIRECT_LOOP",
    category: "indexability",
    title: "Redirect loop detected (URL cycles infinitely)",
    description: "Cyclical redirection makes destination pages completely unreachable.",
    severity: "critical",
    isScoring: true,
    basePenalty: 4.0,
    confidenceType: "confirmed",
    evaluationMode: "deterministic",
    applicableResourceTypes: ["html_page"],
    primaryPageClasses: ["all_html_pages"],
    exclusionFilterDescription: "Triggers on circular redirect paths.",
    diagnosticImpact: "Total loss of access and 100% crawl failure.",
  },
  {
    ruleCode: "SITEMAP_URL_4XX",
    category: "indexability",
    title: "XML sitemap contains broken 4xx URLs",
    description: "Submitting broken URLs in sitemaps wastes crawl budget and signals poor site maintenance.",
    severity: "warning",
    isScoring: true,
    basePenalty: 1.5,
    confidenceType: "confirmed",
    evaluationMode: "deterministic",
    applicableResourceTypes: ["xml_sitemap"],
    primaryPageClasses: ["all_html_pages"],
    exclusionFilterDescription: "Requires sitemap entry returning verified 4xx response.",
    diagnosticImpact: "Wasted crawl budget and lower sitemap trust score.",
  },
  {
    ruleCode: "SITEMAP_URL_REDIRECT",
    category: "indexability",
    title: "XML sitemap lists a URL that redirects (3xx)",
    description: "Sitemaps should contain only canonical 200 OK URLs to guide bot crawling cleanly.",
    severity: "warning",
    isScoring: true,
    basePenalty: 1.0,
    confidenceType: "confirmed",
    evaluationMode: "deterministic",
    applicableResourceTypes: ["xml_sitemap"],
    primaryPageClasses: ["all_html_pages"],
    exclusionFilterDescription: "Requires sitemap entry returning verified 3xx response.",
    diagnosticImpact: "Inefficient crawler resource consumption.",
  },
  {
    ruleCode: "SITEMAP_URL_NOINDEX",
    category: "indexability",
    title: "XML sitemap contains noindexed URLs",
    description: "Submitting a URL in the sitemap while instructing bots not to index it sends conflicting signals.",
    severity: "warning",
    isScoring: true,
    basePenalty: 1.5,
    confidenceType: "confirmed",
    evaluationMode: "deterministic",
    applicableResourceTypes: ["xml_sitemap"],
    primaryPageClasses: ["all_html_pages"],
    exclusionFilterDescription: "Requires sitemap entry with confirmed noindex directive.",
    diagnosticImpact: "Conflicting indexation signals to search engines.",
  },
  {
    ruleCode: "SITEMAP_MALFORMED_XML",
    category: "indexability",
    title: "Malformed XML sitemap file",
    description: "Syntax errors prevent search engines from parsing the XML sitemap file.",
    severity: "critical",
    isScoring: true,
    basePenalty: 3.5,
    confidenceType: "confirmed",
    evaluationMode: "deterministic",
    applicableResourceTypes: ["xml_sitemap"],
    primaryPageClasses: ["all_html_pages"],
    exclusionFilterDescription: "Triggers on non-XML or malformed sitemap files.",
    diagnosticImpact: "Total failure to discover pages through XML sitemap.",
  },

  // =========================================================================
  // 4. LINKS & ARCHITECTURE
  // =========================================================================
  {
    ruleCode: "LINKS_BROKEN_INTERNAL",
    category: "links",
    title: "Broken internal links found (4xx / 5xx)",
    description: "Internal hyperlinks point to erroring or missing pages within the same host.",
    severity: "critical",
    isScoring: true,
    basePenalty: 4.0,
    confidenceType: "confirmed",
    evaluationMode: "deterministic",
    applicableResourceTypes: ["html_page"],
    primaryPageClasses: ["all_html_pages"],
    exclusionFilterDescription: "Requires verified internal 4xx/5xx status response.",
    diagnosticImpact: "Broken user journeys, wasted crawl budget, broken link equity transfer.",
  },
  {
    ruleCode: "LINKS_INTERNAL_TO_REDIRECT",
    category: "links",
    title: "Internal links pointing to a redirect hop (3xx)",
    description: "Internal links should point directly to the destination URL without redirect hops.",
    severity: "opportunity",
    isScoring: true,
    basePenalty: 0.5,
    confidenceType: "confirmed",
    evaluationMode: "deterministic",
    applicableResourceTypes: ["html_page"],
    primaryPageClasses: ["all_html_pages"],
    exclusionFilterDescription: "Triggers when internal navigation link targets a 3xx redirect.",
    diagnosticImpact: "Slows internal site navigation and leaks crawl budget.",
  },
  {
    ruleCode: "LINKS_BROKEN_EXTERNAL",
    category: "links",
    title: "Broken outbound external links",
    description: "Outbound external links return client/server errors or missing destinations.",
    severity: "warning",
    isScoring: true,
    basePenalty: 1.5,
    confidenceType: "likely",
    evaluationMode: "externally_verified",
    applicableResourceTypes: ["html_page"],
    primaryPageClasses: ["all_html_pages"],
    exclusionFilterDescription: "Zero penalty for bot-shielded, rate-limited, or inconclusive targets.",
    diagnosticImpact: "Poor user experience and degraded domain trust signals.",
  },
  {
    ruleCode: "LINKS_EMPTY_ANCHOR",
    category: "links",
    title: "Internal links with missing accessible link name",
    description: "Internal anchor has no text, aria-label, or child image alt.",
    severity: "warning",
    isScoring: true,
    basePenalty: 1.5,
    confidenceType: "confirmed",
    evaluationMode: "deterministic",
    applicableResourceTypes: ["html_page"],
    primaryPageClasses: ["all_html_pages"],
    exclusionFilterDescription: "Excluded on placeholder hash controls.",
    diagnosticImpact: "Search crawlers cannot determine anchor context.",
  },
  {
    ruleCode: "LINKS_NON_DESCRIPTIVE_ANCHOR",
    category: "links",
    title: "Non-descriptive internal anchor text (e.g. 'click here')",
    description: "Anchor uses generic words like 'click here' or 'read more'.",
    severity: "opportunity",
    isScoring: true,
    basePenalty: 0.5,
    confidenceType: "heuristic",
    evaluationMode: "heuristic",
    applicableResourceTypes: ["html_page"],
    primaryPageClasses: ["all_html_pages"],
    exclusionFilterDescription: "Excluded on descriptive phrases containing keywords.",
    diagnosticImpact: "Sub-optimal internal anchor equity and keyword signal.",
  },
  {
    ruleCode: "CODE_PLACEHOLDER_ANCHOR",
    category: "code_validation",
    title: "Placeholder interactive controls (href='#')",
    description: "Anchor tags use href='#' instead of semantic button elements.",
    severity: "opportunity",
    isScoring: true,
    basePenalty: 0.5,
    confidenceType: "confirmed",
    evaluationMode: "deterministic",
    applicableResourceTypes: ["html_page"],
    primaryPageClasses: ["all_html_pages"],
    exclusionFilterDescription: "Excluded on valid deep anchor targets.",
    diagnosticImpact: "Semantically invalid interactive elements.",
  },

  // =========================================================================
  // 5. ASSETS & PERFORMANCE
  // =========================================================================
  {
    ruleCode: "ASSET_MISSING_ALT",
    category: "page_speed_assets",
    title: "Images missing alt text",
    description: "Image tag lacks an alt attribute describing image contents.",
    severity: "warning",
    isScoring: true,
    basePenalty: 1.5,
    confidenceType: "confirmed",
    evaluationMode: "deterministic",
    applicableResourceTypes: ["html_page"],
    primaryPageClasses: ["all_html_pages"],
    exclusionFilterDescription: "Excluded on non-HTML resources.",
    diagnosticImpact: "Accessibility failure and loss of image search relevance.",
  },
  {
    ruleCode: "IMAGE_LINK_MISSING_ALT",
    category: "page_speed_assets",
    title: "Linked image missing alt text and accessible link name",
    description: "When an image is wrapped in an anchor without text or alt, bots cannot determine anchor context.",
    severity: "warning",
    isScoring: true,
    basePenalty: 1.5,
    confidenceType: "confirmed",
    evaluationMode: "deterministic",
    applicableResourceTypes: ["html_page"],
    primaryPageClasses: ["all_html_pages"],
    exclusionFilterDescription: "Excluded when enclosing anchor has accessible aria-label.",
    diagnosticImpact: "Empty anchor equity transfer across internal links.",
  },
  {
    ruleCode: "IMAGE_BROKEN",
    category: "page_speed_assets",
    title: "Broken embedded image (returns 4xx/5xx HTTP error)",
    description: "Broken images create a poor user experience and display visual error artifacts.",
    severity: "warning",
    isScoring: true,
    basePenalty: 1.5,
    confidenceType: "confirmed",
    evaluationMode: "deterministic",
    applicableResourceTypes: ["html_page"],
    primaryPageClasses: ["all_html_pages"],
    exclusionFilterDescription: "Requires verified HTTP 4xx/5xx status on image URL.",
    diagnosticImpact: "Visual broken UI and failed image SEO indexing.",
  },
  {
    ruleCode: "ASSET_MISSING_DIMENSIONS",
    category: "page_speed_assets",
    title: "Images missing width and height attributes",
    description: "Image tag lacks explicit width and height attributes, risking layout shift (CLS).",
    severity: "opportunity",
    isScoring: true,
    basePenalty: 0.5,
    confidenceType: "confirmed",
    evaluationMode: "deterministic",
    applicableResourceTypes: ["html_page"],
    primaryPageClasses: ["all_html_pages"],
    exclusionFilterDescription: "Excluded on SVG images.",
    diagnosticImpact: "Cumulative Layout Shift (CLS) during page render.",
  },
  {
    ruleCode: "RESOURCE_BROKEN_SCRIPT",
    category: "code_validation",
    title: "Broken JavaScript resource (<script src> returns 4xx/5xx)",
    description: "Failed script loads can break page interactivity, client-side rendering, and tracking.",
    severity: "critical",
    isScoring: true,
    basePenalty: 3.5,
    confidenceType: "confirmed",
    evaluationMode: "deterministic",
    applicableResourceTypes: ["html_page"],
    primaryPageClasses: ["all_html_pages"],
    exclusionFilterDescription: "Requires verified HTTP 4xx/5xx status on script URL.",
    diagnosticImpact: "Broken client-side JavaScript execution and rendering errors.",
  },
  {
    ruleCode: "RESOURCE_BROKEN_STYLESHEET",
    category: "code_validation",
    title: "Broken stylesheet resource (<link rel='stylesheet'> returns 4xx/5xx)",
    description: "Missing CSS files result in unstyled page renders and severe layout instability.",
    severity: "critical",
    isScoring: true,
    basePenalty: 3.5,
    confidenceType: "confirmed",
    evaluationMode: "deterministic",
    applicableResourceTypes: ["html_page"],
    primaryPageClasses: ["all_html_pages"],
    exclusionFilterDescription: "Requires verified HTTP 4xx/5xx status on CSS URL.",
    diagnosticImpact: "Unstyled page renders and massive layout shift.",
  },
  {
    ruleCode: "PERF_LARGE_HTML_PAYLOAD",
    category: "page_speed_assets",
    title: "Excessively large raw HTML document payload (> 2 MB)",
    description: "Very large HTML documents slow DOM parsing, delay TTFB, and increase memory consumption.",
    severity: "opportunity",
    isScoring: true,
    basePenalty: 0.5,
    confidenceType: "heuristic",
    evaluationMode: "deterministic",
    applicableResourceTypes: ["html_page"],
    primaryPageClasses: ["all_html_pages"],
    exclusionFilterDescription: "Triggers when raw HTML exceeds 2 MB.",
    diagnosticImpact: "Slow initial DOM parsing and delayed Core Web Vitals.",
  },
  {
    ruleCode: "PERF_SLOW_SERVER_RESPONSE",
    category: "page_speed_assets",
    title: "Slow server response time (TTFB > 1500ms)",
    description: "Initial HTTP response took longer than 1500ms to arrive.",
    severity: "notice",
    isScoring: false,
    basePenalty: 0.0,
    confidenceType: "confirmed",
    evaluationMode: "deterministic",
    applicableResourceTypes: ["html_page"],
    primaryPageClasses: ["all_html_pages"],
    exclusionFilterDescription: "Requires measured TTFB.",
    diagnosticImpact: "Poor user experience and search crawler rate-limiting.",
  },

  // =========================================================================
  // 6. ACCESSIBILITY, MOBILE & TECHNICAL HTML
  // =========================================================================
  {
    ruleCode: "A11Y_MISSING_MAIN_LANDMARK",
    category: "code_validation",
    title: "Missing <main> landmark element",
    description: "Page lacks a semantic <main> tag or [role='main'] container.",
    severity: "warning",
    isScoring: true,
    basePenalty: 1.5,
    confidenceType: "confirmed",
    evaluationMode: "deterministic",
    applicableResourceTypes: ["html_page"],
    primaryPageClasses: ["all_html_pages"],
    exclusionFilterDescription: "Excluded on non-HTML resources.",
    diagnosticImpact: "Screen readers cannot jump directly to primary content.",
  },
  {
    ruleCode: "A11Y_UNLABELLED_FORM_CONTROL",
    category: "code_validation",
    title: "Unlabelled form input control",
    description: "Interactive form input, textarea, or select lacks an associated label or aria-label.",
    severity: "warning",
    isScoring: true,
    basePenalty: 1.5,
    confidenceType: "confirmed",
    evaluationMode: "deterministic",
    applicableResourceTypes: ["html_page"],
    primaryPageClasses: ["all_html_pages"],
    exclusionFilterDescription: "Evaluates only static markup on raw crawl, full DOM on rendered crawl.",
    diagnosticImpact: "Form controls inaccessible to screen readers and assistive technology.",
  },
  {
    ruleCode: "MOBILE_VIEWPORT_MISSING",
    category: "code_validation",
    title: "Missing <meta name='viewport'> tag in <head>",
    description: "Mobile browsers will render the page with desktop scaling, causing usability failure.",
    severity: "critical",
    isScoring: true,
    basePenalty: 3.5,
    confidenceType: "confirmed",
    evaluationMode: "deterministic",
    applicableResourceTypes: ["html_page"],
    primaryPageClasses: ["all_html_pages"],
    exclusionFilterDescription: "Triggers when no viewport meta tag exists in <head>.",
    diagnosticImpact: "Mobile usability failure in Google Mobile-First Indexing.",
  },
  {
    ruleCode: "MOBILE_VIEWPORT_INVALID",
    category: "code_validation",
    title: "Invalid viewport meta tag (missing device-width or disables user zoom)",
    description: "Setting user-scalable=no or fixed pixel widths breaks responsiveness and accessibility.",
    severity: "warning",
    isScoring: true,
    basePenalty: 1.5,
    confidenceType: "confirmed",
    evaluationMode: "deterministic",
    applicableResourceTypes: ["html_page"],
    primaryPageClasses: ["all_html_pages"],
    exclusionFilterDescription: "Triggers on missing width=device-width or user-scalable=no.",
    diagnosticImpact: "Accessibility non-compliance and poor smartphone UX.",
  },
  {
    ruleCode: "HTML_TITLE_MULTIPLE",
    category: "code_validation",
    title: "Multiple <title> tags declared in HTML document",
    description: "Having multiple title tags causes unpredictable snippet selection across search engines.",
    severity: "warning",
    isScoring: true,
    basePenalty: 1.0,
    confidenceType: "confirmed",
    evaluationMode: "deterministic",
    applicableResourceTypes: ["html_page"],
    primaryPageClasses: ["all_html_pages"],
    exclusionFilterDescription: "Triggers when DOM contains 2 or more <title> tags.",
    diagnosticImpact: "Unpredictable search snippet rendering.",
  },
  {
    ruleCode: "HTML_META_DESC_MULTIPLE",
    category: "code_validation",
    title: "Multiple <meta name='description'> tags declared in HTML",
    description: "Multiple meta descriptions confuse search engines when generating SERP preview snippets.",
    severity: "warning",
    isScoring: true,
    basePenalty: 1.0,
    confidenceType: "confirmed",
    evaluationMode: "deterministic",
    applicableResourceTypes: ["html_page"],
    primaryPageClasses: ["all_html_pages"],
    exclusionFilterDescription: "Triggers when DOM contains 2 or more meta description tags.",
    diagnosticImpact: "Unpredictable search description snippets.",
  },

  // =========================================================================
  // 7. SECURITY & WEB HYGIENE
  // =========================================================================
  {
    ruleCode: "SEC_MISSING_NOSNIFF",
    category: "security",
    title: "Missing X-Content-Type-Options header",
    description: "Response lacks X-Content-Type-Options: nosniff header.",
    severity: "opportunity",
    isScoring: true,
    basePenalty: 0.5,
    confidenceType: "confirmed",
    evaluationMode: "deterministic",
    applicableResourceTypes: ["html_page"],
    primaryPageClasses: ["all_html_pages"],
    exclusionFilterDescription: "Requires response header inspection.",
    diagnosticImpact: "MIME-sniffing security vulnerability.",
  },
  {
    ruleCode: "SEC_MIXED_CONTENT",
    category: "security",
    title: "Mixed content (insecure HTTP resources on HTTPS page)",
    description: "Browsers block insecure passive/active HTTP resources on HTTPS origins.",
    severity: "warning",
    isScoring: true,
    basePenalty: 2.0,
    confidenceType: "confirmed",
    evaluationMode: "deterministic",
    applicableResourceTypes: ["html_page"],
    primaryPageClasses: ["all_html_pages"],
    exclusionFilterDescription: "Triggers when HTTPS page loads http:// resources.",
    diagnosticImpact: "Browser mixed content blocking and security warning indicators.",
  },

  // =========================================================================
  // 8. SOCIAL & STRUCTURED DATA (SCHEMA)
  // =========================================================================
  {
    ruleCode: "SCHEMA_MALFORMED_JSON",
    category: "social_schema",
    title: "Malformed JSON-LD structured data script",
    description: "Script tag with type='application/ld+json' contains invalid JSON syntax.",
    severity: "critical",
    isScoring: true,
    basePenalty: 4.0,
    confidenceType: "confirmed",
    evaluationMode: "deterministic",
    applicableResourceTypes: ["html_page"],
    primaryPageClasses: ["all_html_pages"],
    exclusionFilterDescription: "Excluded when no JSON-LD script is present.",
    diagnosticImpact: "Complete rejection of rich snippets by search engines.",
  },
  {
    ruleCode: "SCHEMA_MISSING_TYPE",
    category: "social_schema",
    title: "JSON-LD structured data block missing @type",
    description: "Search engine schema validators reject structured data entities lacking a valid @type.",
    severity: "warning",
    isScoring: true,
    basePenalty: 1.5,
    confidenceType: "confirmed",
    evaluationMode: "deterministic",
    applicableResourceTypes: ["html_page"],
    primaryPageClasses: ["all_html_pages"],
    exclusionFilterDescription: "Triggers on valid JSON-LD missing @type attribute.",
    diagnosticImpact: "Loss of entity graph understanding and rich snippet eligibility.",
  },
  {
    ruleCode: "SCHEMA_INVALID_CONTEXT",
    category: "social_schema",
    title: "JSON-LD structured data block missing schema.org @context",
    description: "Without '@context': 'https://schema.org', parsers cannot map vocabulary terms.",
    severity: "warning",
    isScoring: true,
    basePenalty: 1.5,
    confidenceType: "confirmed",
    evaluationMode: "deterministic",
    applicableResourceTypes: ["html_page"],
    primaryPageClasses: ["all_html_pages"],
    exclusionFilterDescription: "Triggers on JSON-LD missing valid schema.org @context.",
    diagnosticImpact: "Rejection of schema vocabulary mapping.",
  },
  {
    ruleCode: "SOCIAL_INCOMPLETE_OG",
    category: "social_schema",
    title: "Incomplete Open Graph tags (og:title / og:image)",
    description: "Page lacks either og:title or og:image required for social preview cards.",
    severity: "opportunity",
    isScoring: true,
    basePenalty: 0.5,
    confidenceType: "heuristic",
    evaluationMode: "heuristic",
    applicableResourceTypes: ["html_page"],
    primaryPageClasses: ["homepage", "marketing_landing", "article_blog", "active_job", "product_job_detail", "category_listing"],
    exclusionFilterDescription: "Excluded on utility and non-indexable pages.",
    diagnosticImpact: "Degraded appearance when shared on social media and messaging platforms.",
  },

  // =========================================================================
  // 9. INTERNATIONAL SEO / HREFLANG
  // =========================================================================
  {
    ruleCode: "HREFLANG_INVALID_CODE",
    category: "code_validation",
    title: "Invalid language or region code in hreflang annotation",
    description: "Search engines ignore hreflang annotations with invalid ISO 639-1 / ISO 3166-1 codes.",
    severity: "warning",
    isScoring: true,
    basePenalty: 1.5,
    confidenceType: "confirmed",
    evaluationMode: "deterministic",
    applicableResourceTypes: ["html_page"],
    primaryPageClasses: ["all_html_pages"],
    exclusionFilterDescription: "Triggers on non-standard BCP 47 language/region codes.",
    diagnosticImpact: "Search engines ignore localized language targeting.",
  },
  {
    ruleCode: "HREFLANG_MISSING_RETURN",
    category: "code_validation",
    title: "Missing reciprocal return link in hreflang annotation",
    description: "Google ignores hreflang clusters unless both pages reciprocally link to each other.",
    severity: "warning",
    isScoring: true,
    basePenalty: 2.0,
    confidenceType: "confirmed",
    evaluationMode: "deterministic",
    applicableResourceTypes: ["html_page"],
    primaryPageClasses: ["all_html_pages"],
    exclusionFilterDescription: "Requires target page with missing return hreflang tag.",
    diagnosticImpact: "Complete breakdown of regional targeting cluster.",
  },
  {
    ruleCode: "HREFLANG_SELF_REF_MISSING",
    category: "code_validation",
    title: "Missing self-referencing hreflang tag",
    description: "Best practice requires every localized URL to include a self-referencing hreflang tag.",
    severity: "opportunity",
    isScoring: true,
    basePenalty: 0.5,
    confidenceType: "confirmed",
    evaluationMode: "deterministic",
    applicableResourceTypes: ["html_page"],
    primaryPageClasses: ["all_html_pages"],
    exclusionFilterDescription: "Triggers on localized pages missing self-referencing tag.",
    diagnosticImpact: "Potential ambiguity in localized search clustering.",
  },

  // =========================================================================
  // 10. PHASE 6 — ADVANCED TECHNICAL SEO EXPANSION
  // =========================================================================
  {
    ruleCode: "CANONICAL_CHAIN",
    category: "indexability",
    title: "Canonical chain detected (Canonical points to another canonicalized page)",
    description: "Page canonicalizes to a URL that in turn canonicalizes elsewhere, causing search engines to ignore canonicalization.",
    severity: "critical",
    isScoring: true,
    basePenalty: 3.0,
    confidenceType: "confirmed",
    evaluationMode: "deterministic",
    applicableResourceTypes: ["html_page"],
    primaryPageClasses: ["all_html_pages"],
    exclusionFilterDescription: "Excluded on self-canonical and non-canonicalizing pages.",
    diagnosticImpact: "Search engine ignores canonical instruction or selects unintended canonical URL.",
  },
  {
    ruleCode: "CANONICAL_RELATIVE",
    category: "indexability",
    title: "Relative canonical URL tag syntax (<link rel='canonical' href='/path'>)",
    description: "Canonical link element uses a relative path instead of an absolute URL. While valid when resolving against the document base, absolute URLs are recommended to prevent multi-domain and protocol ambiguity.",
    severity: "opportunity",
    isScoring: false,
    basePenalty: 0.0,
    confidenceType: "confirmed",
    evaluationMode: "deterministic",
    applicableResourceTypes: ["html_page"],
    primaryPageClasses: ["all_html_pages"],
    exclusionFilterDescription: "Triggers on relative href in canonical tags; non-scoring informational guidance.",
    diagnosticImpact: "Informational best practice; relative canonicals are not inherently invalid.",
  },
  {
    ruleCode: "ROBOTS_HEADER_META_CONFLICT",
    category: "indexability",
    title: "Conflicting indexing directives between HTTP X-Robots-Tag and HTML Meta Robots",
    description: "HTTP header X-Robots-Tag specifies noindex while HTML meta robots specifies index (or vice-versa).",
    severity: "critical",
    isScoring: true,
    basePenalty: 4.0,
    confidenceType: "confirmed",
    evaluationMode: "deterministic",
    applicableResourceTypes: ["html_page"],
    primaryPageClasses: ["all_html_pages"],
    exclusionFilterDescription: "Requires contradictory directives between HTTP response headers and DOM meta tags.",
    diagnosticImpact: "Unpredictable search engine indexing behavior and accidental de-indexing.",
  },
  {
    ruleCode: "INTERNAL_LINK_TO_NOINDEX",
    category: "links",
    title: "Internal links pointing to noindex pages",
    description: "Standard internal hyperlinks point to pages configured with noindex, wasting crawl equity.",
    severity: "warning",
    isScoring: true,
    basePenalty: 1.5,
    confidenceType: "confirmed",
    evaluationMode: "deterministic",
    applicableResourceTypes: ["html_page"],
    primaryPageClasses: ["all_indexable_content"],
    exclusionFilterDescription: "Excluded on external links and indexable targets.",
    diagnosticImpact: "Crawl budget waste and dilution of internal PageRank.",
  },
  {
    ruleCode: "ROBOTS_BLOCKED_IMPORTANT_RESOURCE",
    category: "indexability",
    title: "Robots.txt blocks critical CSS or JavaScript rendering resources",
    description: "Robots.txt disallows crawler access to core CSS/JS files needed by search engines to render the page.",
    severity: "critical",
    isScoring: true,
    basePenalty: 2.5,
    confidenceType: "likely",
    evaluationMode: "deterministic",
    applicableResourceTypes: ["html_page"],
    primaryPageClasses: ["all_html_pages"],
    exclusionFilterDescription: "Triggers when primary stylesheets or script assets match robots.txt Disallow rules.",
    diagnosticImpact: "Search engine fails to render mobile layout, causing mobile indexing penalties.",
  },
  {
    ruleCode: "ROBOTS_SITEMAP_MISSING",
    category: "indexability",
    title: "Robots.txt missing Sitemap reference",
    description: "Robots.txt file does not declare the XML sitemap location using a Sitemap directive.",
    severity: "opportunity",
    isScoring: false,
    basePenalty: 0.0,
    confidenceType: "confirmed",
    evaluationMode: "deterministic",
    applicableResourceTypes: ["html_page"],
    primaryPageClasses: ["homepage"],
    exclusionFilterDescription: "Checked at site origin level; non-scoring informational guidance.",
    diagnosticImpact: "Helpful discovery assistance; does not reduce organic search rankings directly.",
  },
  {
    ruleCode: "SITEMAP_URL_BLOCKED_BY_ROBOTS",
    category: "sitemaps",
    title: "Sitemap contains URL disallowed in robots.txt",
    description: "A URL submitted in the XML Sitemap is blocked from crawling by a robots.txt Disallow directive.",
    severity: "critical",
    isScoring: true,
    basePenalty: 3.0,
    confidenceType: "confirmed",
    evaluationMode: "deterministic",
    applicableResourceTypes: ["sitemap_index", "sitemap_xml"],
    primaryPageClasses: ["all_sitemap_urls"],
    exclusionFilterDescription: "Requires sitemap URL matching active robots.txt disallow pattern.",
    diagnosticImpact: "Direct contradiction between submission intent and crawler instruction.",
  },
  {
    ruleCode: "SITEMAP_URL_NON_CANONICAL",
    category: "sitemaps",
    title: "Sitemap contains non-self-canonical URL (URL canonicalizes elsewhere)",
    description: "XML sitemap lists a URL that declares a canonical tag pointing to a different URL.",
    severity: "warning",
    isScoring: true,
    basePenalty: 2.0,
    confidenceType: "confirmed",
    evaluationMode: "deterministic",
    applicableResourceTypes: ["sitemap_index", "sitemap_xml"],
    primaryPageClasses: ["all_sitemap_urls"],
    exclusionFilterDescription: "Excluded on self-canonical sitemap URLs.",
    diagnosticImpact: "Conflicting indexation signals and wasted sitemap crawl budget.",
  },
  {
    ruleCode: "SITEMAP_URL_DUPLICATE",
    category: "sitemaps",
    title: "Duplicate URL entries declared in XML sitemap",
    description: "The exact same URL is declared multiple times within the XML sitemap.",
    severity: "opportunity",
    isScoring: true,
    basePenalty: 0.5,
    confidenceType: "confirmed",
    evaluationMode: "deterministic",
    applicableResourceTypes: ["sitemap_index", "sitemap_xml"],
    primaryPageClasses: ["all_sitemap_urls"],
    exclusionFilterDescription: "Triggers on redundant <loc> entries.",
    diagnosticImpact: "Wasted sitemap file size and parser overhead.",
  },
  {
    ruleCode: "URL_NON_NORMALIZED_INTERNAL_LINK",
    category: "code_validation",
    title: "Internal links use non-normalized URL variants (casing, trailing slashes, default files)",
    description: "Internal links point to inconsistent casing, duplicate trailing slashes, or default filenames like /index.html.",
    severity: "opportunity",
    isScoring: false,
    basePenalty: 0.0,
    confidenceType: "heuristic",
    evaluationMode: "deterministic",
    applicableResourceTypes: ["html_page"],
    primaryPageClasses: ["all_indexable_content"],
    exclusionFilterDescription: "Excluded on standard normalized clean URLs.",
    diagnosticImpact: "Splits crawl equity and triggers unnecessary internal redirect hops.",
  },
  {
    ruleCode: "REDIRECT_TO_BROKEN_4XX",
    category: "redirects",
    title: "Redirect target resolves to broken 4xx or 5xx error",
    description: "A 301/302 redirect points to a destination that returns a 4xx client error or 5xx server error.",
    severity: "critical",
    isScoring: true,
    basePenalty: 3.5,
    confidenceType: "confirmed",
    evaluationMode: "deterministic",
    applicableResourceTypes: ["html_page"],
    primaryPageClasses: ["all_html_pages"],
    exclusionFilterDescription: "Requires redirect chain terminating in 4xx or 5xx status.",
    diagnosticImpact: "Dead-end crawl trap and complete link equity destruction.",
  },
  {
    ruleCode: "REDIRECT_META_REFRESH",
    category: "redirects",
    title: "Client-side HTML Meta Refresh redirect tag detected",
    description: "Page executes a redirect using <meta http-equiv='refresh'> instead of server-side 301.",
    severity: "warning",
    isScoring: true,
    basePenalty: 1.5,
    confidenceType: "confirmed",
    evaluationMode: "deterministic",
    applicableResourceTypes: ["html_page"],
    primaryPageClasses: ["all_html_pages"],
    exclusionFilterDescription: "Triggers when meta http-equiv='refresh' element exists.",
    diagnosticImpact: "Delayed page indexing and sub-optimal search crawler redirection.",
  },
  {
    ruleCode: "HTTP_STATUS_5XX_SERVER_ERROR",
    category: "code_validation",
    title: "Server 5xx Internal Error on crawled page",
    description: "Page returns HTTP status 500, 502, 503, or 504 server failure.",
    severity: "critical",
    isScoring: true,
    basePenalty: 4.0,
    confidenceType: "confirmed",
    evaluationMode: "deterministic",
    applicableResourceTypes: ["html_page"],
    primaryPageClasses: ["all_html_pages"],
    exclusionFilterDescription: "Triggers on response status >= 500.",
    diagnosticImpact: "Complete crawler blockage and immediate ranking degradation.",
  },
  {
    ruleCode: "RENDER_CRITICAL_METADATA_DISCREPANCY",
    category: "indexability",
    title: "Critical indexing metadata differs between raw HTML and JavaScript-rendered DOM",
    description: "Client-side JavaScript alters canonical URL or robots indexing directives after initial HTML load.",
    severity: "warning",
    isScoring: true,
    basePenalty: 2.0,
    confidenceType: "confirmed",
    evaluationMode: "deterministic",
    applicableResourceTypes: ["html_page"],
    primaryPageClasses: ["all_html_pages"],
    exclusionFilterDescription: "Requires material difference in canonical or robots between raw and rendered states.",
    diagnosticImpact: "Search engines reading raw HTML index conflicting metadata compared to rendered engines.",
  },
  {
    ruleCode: "SCHEMA_BREADCRUMBLIST_INVALID",
    category: "code_validation",
    title: "Malformed BreadcrumbList schema structure or missing item positions",
    description: "BreadcrumbList structured data is missing itemListElement, missing position properties, or positions are non-sequential.",
    severity: "warning",
    isScoring: true,
    basePenalty: 1.5,
    confidenceType: "confirmed",
    evaluationMode: "deterministic",
    applicableResourceTypes: ["html_page"],
    primaryPageClasses: ["all_html_pages"],
    exclusionFilterDescription: "Triggers on structural BreadcrumbList errors in JSON-LD.",
    diagnosticImpact: "Loss of breadcrumb rich snippets in Google Search results.",
  },
  {
    ruleCode: "HREFLANG_TARGET_NON_INDEXABLE",
    category: "code_validation",
    title: "Hreflang alternate points to a non-indexable URL (4xx, redirect, or noindex)",
    description: "An alternate hreflang tag references a URL that returns 4xx, redirects, or is marked noindex.",
    severity: "critical",
    isScoring: true,
    basePenalty: 3.0,
    confidenceType: "confirmed",
    evaluationMode: "deterministic",
    applicableResourceTypes: ["html_page"],
    primaryPageClasses: ["all_html_pages"],
    exclusionFilterDescription: "Requires hreflang target resolving to non-200 or non-indexable destination.",
    diagnosticImpact: "Google ignores regional and international localization clusters.",
  },
  {
    ruleCode: "IMAGE_ABOVE_FOLD_LAZY_LOADED",
    category: "page_speed_assets",
    title: "Above-the-fold hero or header image configured with loading='lazy'",
    description: "Primary header logo or first prominent hero image uses loading='lazy', potentially delaying LCP.",
    severity: "opportunity",
    isScoring: false,
    basePenalty: 0.0,
    confidenceType: "heuristic",
    evaluationMode: "heuristic",
    applicableResourceTypes: ["html_page"],
    primaryPageClasses: ["all_indexable_content"],
    exclusionFilterDescription: "Excluded on below-fold images and eager-loaded hero images.",
    diagnosticImpact: "Performance / Core Web Vitals optimization advisory; non-scoring in Phase 6.",
  },

  // =========================================================================
  // 11. PHASE 7 — PERFORMANCE & CORE WEB VITALS INTELLIGENCE
  // =========================================================================
  {
    ruleCode: "FIELD_LCP_POOR",
    category: "page_speed_assets",
    title: "Real-User Largest Contentful Paint (LCP) is Poor (> 4.0s)",
    description: "Aggregated Chrome User Experience Report (CrUX) field data indicates that over 25% of real users experience LCP > 4.0s.",
    severity: "warning",
    isScoring: true,
    basePenalty: 3.0,
    confidenceType: "confirmed",
    evaluationMode: "externally_verified",
    applicableResourceTypes: ["html_page"],
    primaryPageClasses: ["all_indexable_content"],
    exclusionFilterDescription: "Requires CrUX 75th percentile LCP > 4000ms.",
    diagnosticImpact: "Real-user visual loading delay; primary Core Web Vitals ranking signal.",
  },
  {
    ruleCode: "FIELD_INP_POOR",
    category: "page_speed_assets",
    title: "Real-User Interaction to Next Paint (INP) is Poor (> 500ms)",
    description: "Chrome User Experience Report (CrUX) indicates poor real-user interaction responsiveness exceeding 500ms.",
    severity: "warning",
    isScoring: true,
    basePenalty: 3.0,
    confidenceType: "confirmed",
    evaluationMode: "externally_verified",
    applicableResourceTypes: ["html_page"],
    primaryPageClasses: ["all_indexable_content"],
    exclusionFilterDescription: "Requires CrUX 75th percentile INP > 500ms.",
    diagnosticImpact: "High UI latency, unresponsive user interactions, failing Core Web Vitals threshold.",
  },
  {
    ruleCode: "FIELD_CLS_POOR",
    category: "page_speed_assets",
    title: "Real-User Cumulative Layout Shift (CLS) is Poor (> 0.25)",
    description: "Real-user field data indicates severe visual instability during page load exceeding 0.25.",
    severity: "warning",
    isScoring: true,
    basePenalty: 3.0,
    confidenceType: "confirmed",
    evaluationMode: "externally_verified",
    applicableResourceTypes: ["html_page"],
    primaryPageClasses: ["all_indexable_content"],
    exclusionFilterDescription: "Requires CrUX 75th percentile CLS > 0.25.",
    diagnosticImpact: "Content shifts during loading, causing accidental user clicks and poor UX.",
  },
  {
    ruleCode: "FIELD_LCP_NEEDS_IMPROVEMENT",
    category: "page_speed_assets",
    title: "Real-User Largest Contentful Paint (LCP) Needs Improvement (2.5s–4.0s)",
    description: "Real-user 75th percentile LCP is between 2.5s and 4.0s, failing the Google Good threshold (<= 2.5s).",
    severity: "warning",
    isScoring: true,
    basePenalty: 1.5,
    confidenceType: "confirmed",
    evaluationMode: "externally_verified",
    applicableResourceTypes: ["html_page"],
    primaryPageClasses: ["all_indexable_content"],
    exclusionFilterDescription: "Requires CrUX 75th percentile LCP between 2501ms and 4000ms.",
    diagnosticImpact: "Moderate loading delay preventing page from passing Core Web Vitals.",
  },
  {
    ruleCode: "FIELD_INP_NEEDS_IMPROVEMENT",
    category: "page_speed_assets",
    title: "Real-User Interaction to Next Paint (INP) Needs Improvement (200ms–500ms)",
    description: "Real-user 75th percentile INP is between 200ms and 500ms, exceeding the 200ms Good target.",
    severity: "warning",
    isScoring: true,
    basePenalty: 1.5,
    confidenceType: "confirmed",
    evaluationMode: "externally_verified",
    applicableResourceTypes: ["html_page"],
    primaryPageClasses: ["all_indexable_content"],
    exclusionFilterDescription: "Requires CrUX 75th percentile INP between 201ms and 500ms.",
    diagnosticImpact: "Sub-optimal UI responsiveness under user input.",
  },
  {
    ruleCode: "FIELD_CLS_NEEDS_IMPROVEMENT",
    category: "page_speed_assets",
    title: "Real-User Cumulative Layout Shift (CLS) Needs Improvement (0.10–0.25)",
    description: "Real-user visual layout shift exceeds 0.10, causing noticeable page movement as assets load.",
    severity: "warning",
    isScoring: true,
    basePenalty: 1.5,
    confidenceType: "confirmed",
    evaluationMode: "externally_verified",
    applicableResourceTypes: ["html_page"],
    primaryPageClasses: ["all_indexable_content"],
    exclusionFilterDescription: "Requires CrUX 75th percentile CLS between 0.101 and 0.25.",
    diagnosticImpact: "Visual instability during page load.",
  },
  {
    ruleCode: "LAB_LCP_POOR",
    category: "page_speed_assets",
    title: "Simulated Lighthouse LCP is Poor (> 4.0s)",
    description: "Lab simulation under throttled mobile network conditions measures Largest Contentful Paint > 4.0s.",
    severity: "warning",
    isScoring: false,
    basePenalty: 0.0,
    confidenceType: "likely",
    evaluationMode: "deterministic",
    applicableResourceTypes: ["html_page"],
    primaryPageClasses: ["all_indexable_content"],
    exclusionFilterDescription: "Requires Lighthouse simulated LCP > 4000ms.",
    diagnosticImpact: "Synthetic lab diagnostic finding; non-scoring to prevent double penalty against field metrics.",
  },
  {
    ruleCode: "LAB_CLS_POOR",
    category: "page_speed_assets",
    title: "Simulated Lighthouse CLS is Poor (> 0.25)",
    description: "Lab audit detects layout shifts > 0.25 occurring during initial synthetic page render.",
    severity: "warning",
    isScoring: false,
    basePenalty: 0.0,
    confidenceType: "likely",
    evaluationMode: "deterministic",
    applicableResourceTypes: ["html_page"],
    primaryPageClasses: ["all_indexable_content"],
    exclusionFilterDescription: "Requires Lighthouse simulated CLS > 0.25.",
    diagnosticImpact: "Synthetic lab diagnostic finding; non-scoring to prevent double penalty against field metrics.",
  },
  {
    ruleCode: "LAB_TBT_HIGH",
    category: "page_speed_assets",
    title: "High Total Blocking Time in lab simulation (> 600ms)",
    description: "Total Blocking Time (TBT) exceeds 600ms, indicating heavy JavaScript execution blocking the main thread.",
    severity: "warning",
    isScoring: false,
    basePenalty: 0.0,
    confidenceType: "likely",
    evaluationMode: "deterministic",
    applicableResourceTypes: ["html_page"],
    primaryPageClasses: ["all_indexable_content"],
    exclusionFilterDescription: "Requires Lighthouse simulated TBT > 600ms.",
    diagnosticImpact: "Synthetic lab diagnostic finding; supporting evidence for JavaScript execution overhead.",
  },
  {
    ruleCode: "LAB_TTFB_SLOW",
    category: "page_speed_assets",
    title: "Slow initial server response time / TTFB (> 1800ms)",
    description: "Server response time for the initial HTML document exceeds 1.8 seconds in lab measurements.",
    severity: "warning",
    isScoring: false,
    basePenalty: 0.0,
    confidenceType: "likely",
    evaluationMode: "deterministic",
    applicableResourceTypes: ["html_page"],
    primaryPageClasses: ["all_indexable_content"],
    exclusionFilterDescription: "Requires lab server response time > 1800ms.",
    diagnosticImpact: "Performance guidance; non-scoring to prevent double penalty.",
  },
  {
    ruleCode: "PERF_RENDER_BLOCKING_RESOURCES",
    category: "page_speed_assets",
    title: "Render-blocking resources delaying first content paint",
    description: "Synchronous stylesheets or scripts in the HTML document head block the browser from painting content.",
    severity: "opportunity",
    isScoring: false,
    basePenalty: 0.0,
    confidenceType: "likely",
    evaluationMode: "deterministic",
    applicableResourceTypes: ["html_page"],
    primaryPageClasses: ["all_indexable_content"],
    exclusionFilterDescription: "Requires render-blocking resource savings > 300ms.",
    diagnosticImpact: "Remediation opportunity for LCP root cause; non-scoring.",
  },
  {
    ruleCode: "PERF_LCP_IMAGE_UNOPTIMIZED",
    category: "page_speed_assets",
    title: "LCP hero image delivery is unoptimized",
    description: "The primary hero image acting as the Largest Contentful Paint candidate is unoptimized or lazy-loaded.",
    severity: "opportunity",
    isScoring: false,
    basePenalty: 0.0,
    confidenceType: "likely",
    evaluationMode: "deterministic",
    applicableResourceTypes: ["html_page"],
    primaryPageClasses: ["all_indexable_content"],
    exclusionFilterDescription: "Triggers on unoptimized or lazy-loaded hero element.",
    diagnosticImpact: "Remediation opportunity for LCP root cause; non-scoring.",
  },
  {
    ruleCode: "PERF_UNUSED_JAVASCRIPT_HIGH",
    category: "page_speed_assets",
    title: "High volume of unused JavaScript loaded on page (> 100KB)",
    description: "Significant portions of downloaded JavaScript are never executed during initial page rendering.",
    severity: "opportunity",
    isScoring: false,
    basePenalty: 0.0,
    confidenceType: "heuristic",
    evaluationMode: "heuristic",
    applicableResourceTypes: ["html_page"],
    primaryPageClasses: ["all_indexable_content"],
    exclusionFilterDescription: "Requires unused JavaScript wasted bytes > 100KB.",
    diagnosticImpact: "Remediation opportunity for script efficiency; non-scoring.",
  },
  {
    ruleCode: "PERF_DOM_SIZE_EXCESSIVE",
    category: "page_speed_assets",
    title: "Excessive DOM size (> 1,400 elements)",
    description: "A large DOM tree increases memory usage, slows layout and style calculations, and harms interaction latency.",
    severity: "opportunity",
    isScoring: false,
    basePenalty: 0.0,
    confidenceType: "confirmed",
    evaluationMode: "deterministic",
    applicableResourceTypes: ["html_page"],
    primaryPageClasses: ["all_indexable_content"],
    exclusionFilterDescription: "Requires total DOM nodes > 1400.",
    diagnosticImpact: "Engineering / performance opportunity; non-scoring.",
  },
  {
    ruleCode: "PERF_THIRD_PARTY_BLOCKING",
    category: "page_speed_assets",
    title: "Third-party scripts causing main thread execution delay (> 400ms)",
    description: "Third-party tracking, analytics, or chat widgets significantly block the browser main thread.",
    severity: "opportunity",
    isScoring: false,
    basePenalty: 0.0,
    confidenceType: "likely",
    evaluationMode: "deterministic",
    applicableResourceTypes: ["html_page"],
    primaryPageClasses: ["all_indexable_content"],
    exclusionFilterDescription: "Requires aggregate 3rd party blocking time > 400ms.",
    diagnosticImpact: "Remediation opportunity for third-party script management; non-scoring.",
  },
  // =========================================================================
  // 11. PHASE 25 ENTERPRISE CLIENT AUDIT PARITY EXPANSIONS (Rules 96 - 101)
  // =========================================================================
  {
    ruleCode: "HTML_LANG_MISSING",
    category: "code_validation",
    title: "Missing <html> lang attribute",
    description: "The <html> element lacks a valid, non-empty lang attribute declaring the document language.",
    severity: "warning",
    isScoring: true,
    basePenalty: 1.5,
    confidenceType: "confirmed",
    evaluationMode: "deterministic",
    applicableResourceTypes: ["html_page"],
    primaryPageClasses: ["all_html_pages"],
    exclusionFilterDescription: "Excluded on non-HTML resources and utility endpoints.",
    diagnosticImpact: "Impaired internationalization, screen-reader mispronunciation, and ambiguous search locale.",
  },
  {
    ruleCode: "A11Y_BUTTON_NAME_MISSING",
    category: "code_validation",
    title: "Button missing accessible name",
    description: "Interactive <button> or button-role control lacks an accessible name (text, aria-label, aria-labelledby, or title).",
    severity: "warning",
    isScoring: true,
    basePenalty: 1.5,
    confidenceType: "confirmed",
    evaluationMode: "deterministic",
    applicableResourceTypes: ["html_page"],
    primaryPageClasses: ["all_html_pages"],
    exclusionFilterDescription: "Excluded on utility endpoints.",
    diagnosticImpact: "Critical accessibility failure; assistive tech cannot announce button function.",
  },
  {
    ruleCode: "A11Y_IFRAME_TITLE_MISSING",
    category: "code_validation",
    title: "Iframe missing title attribute",
    description: "Embedded <iframe> element is missing an accessible, descriptive title attribute.",
    severity: "opportunity",
    isScoring: true,
    basePenalty: 0.5,
    confidenceType: "confirmed",
    evaluationMode: "deterministic",
    applicableResourceTypes: ["html_page"],
    primaryPageClasses: ["all_html_pages"],
    exclusionFilterDescription: "Excluded on hidden or non-content tracking iframes.",
    diagnosticImpact: "WCAG accessibility gap for assistive technology navigation.",
  },
  {
    ruleCode: "IMAGE_OVERSIZED_FILE",
    category: "page_speed_assets",
    title: "Oversized image file (> 250 KB)",
    description: "Image file transfer size exceeds 250 KB, slowing down page rendering and consuming excess user data.",
    severity: "opportunity",
    isScoring: true,
    basePenalty: 0.5,
    confidenceType: "confirmed",
    evaluationMode: "deterministic",
    applicableResourceTypes: ["html_page"],
    primaryPageClasses: ["all_html_pages"],
    exclusionFilterDescription: "Applies to image assets with byteSize > 250 KB.",
    diagnosticImpact: "Degrades Largest Contentful Paint (LCP) and mobile page load performance.",
  },
  {
    ruleCode: "SOCIAL_TWITTER_CARD_MISSING",
    category: "social_schema",
    title: "Missing Twitter Card metadata",
    description: "Indexable page contains social metadata or is an article/landing page but lacks an explicit twitter:card tag.",
    severity: "opportunity",
    isScoring: true,
    basePenalty: 0.5,
    confidenceType: "confirmed",
    evaluationMode: "deterministic",
    applicableResourceTypes: ["html_page"],
    primaryPageClasses: ["all_indexable_content"],
    exclusionFilterDescription: "Applies to indexable marketing/article pages with social presence.",
    diagnosticImpact: "Sub-optimal social media preview sharing on X/Twitter.",
  },
  {
    ruleCode: "PERF_COMPRESSION_DISABLED",
    category: "page_speed_assets",
    title: "Text compression disabled on large HTML response",
    description: "HTML document exceeds 10 KB but is transferred without GZIP, Brotli, or Deflate encoding.",
    severity: "warning",
    isScoring: true,
    basePenalty: 1.5,
    confidenceType: "confirmed",
    evaluationMode: "deterministic",
    applicableResourceTypes: ["html_page"],
    primaryPageClasses: ["all_html_pages"],
    exclusionFilterDescription: "Applies to HTML responses > 10 KB without compression headers.",
    diagnosticImpact: "Increases HTML transfer time and inflates initial server response latency.",
  },
  {
    ruleCode: "HTML_CHARSET_MISSING",
    category: "code_validation",
    title: "Missing character encoding declaration (<meta charset>)",
    description: "HTML document does not declare a character encoding in <meta charset>, <meta http-equiv>, or HTTP Content-Type header.",
    severity: "warning",
    isScoring: true,
    basePenalty: 1.5,
    confidenceType: "confirmed",
    evaluationMode: "deterministic",
    applicableResourceTypes: ["html_page"],
    primaryPageClasses: ["all_html_pages"],
    exclusionFilterDescription: "Excluded on non-HTML resources and utility endpoints.",
    diagnosticImpact: "Causes garbled text rendering (mojibake) and character decoding vulnerabilities.",
  },
  {
    ruleCode: "SEC_TARGET_BLANK_NOOPENER",
    category: "security",
    title: "External target='_blank' link missing rel='noopener/noreferrer'",
    description: "External hyperlinks opening in new browsing contexts lack explicit rel='noopener' or rel='noreferrer' attributes.",
    severity: "notice",
    isScoring: false,
    basePenalty: 0,
    confidenceType: "confirmed",
    evaluationMode: "deterministic",
    applicableResourceTypes: ["html_page"],
    primaryPageClasses: ["all_html_pages"],
    exclusionFilterDescription: "Applies to external cross-origin links with target='_blank'.",
    diagnosticImpact: "Security best practice to prevent reverse tabnabbing and window.opener manipulation in legacy clients.",
  },
  {
    ruleCode: "HTML_DEPRECATED_TAGS",
    category: "code_validation",
    title: "Deprecated / obsolete HTML tags detected",
    description: "HTML document contains deprecated presentational tags (such as <marquee>, <blink>, <font>, <center>, <strike>).",
    severity: "notice",
    isScoring: false,
    basePenalty: 0,
    confidenceType: "confirmed",
    evaluationMode: "deterministic",
    applicableResourceTypes: ["html_page"],
    primaryPageClasses: ["all_html_pages"],
    exclusionFilterDescription: "Excluded on utility endpoints.",
    diagnosticImpact: "Violates HTML5 standards and impairs maintainability and screen-reader accessibility.",
  },
  {
    ruleCode: "SOCIAL_OPENGRAPH_FALLBACK",
    category: "social_schema",
    title: "Incomplete Open Graph fallback metadata",
    description: "Page relies on Open Graph metadata for social link previews but lacks core properties (og:title, og:image, og:description).",
    severity: "notice",
    isScoring: false,
    basePenalty: 0,
    confidenceType: "confirmed",
    evaluationMode: "deterministic",
    applicableResourceTypes: ["html_page"],
    primaryPageClasses: ["all_indexable_content"],
    exclusionFilterDescription: "Applies to indexable marketing/content pages.",
    diagnosticImpact: "Produces incomplete or malformed preview snippets when shared on social networks.",
  },
  {
    ruleCode: "ASSET_LAZY_LOADING_MISSING",
    category: "page_speed_assets",
    title: "Below-the-fold images missing loading='lazy'",
    description: "Content images located below the initial viewport lack native loading='lazy' attributes.",
    severity: "notice",
    isScoring: false,
    basePenalty: 0,
    confidenceType: "confirmed",
    evaluationMode: "deterministic",
    applicableResourceTypes: ["html_page"],
    primaryPageClasses: ["all_html_pages"],
    exclusionFilterDescription: "Safely exempts first 2 images, hero images, logos, icons, and preloaded assets.",
    diagnosticImpact: "Slows initial page rendering and wastes bandwidth on unviewed content images.",
  },
  {
    ruleCode: "IMAGE_LEGACY_FORMAT",
    category: "page_speed_assets",
    title: "Large legacy image format (PNG/JPEG > 100 KB)",
    description: "Large image assets are served in legacy formats (PNG/JPEG) where modern WebP or AVIF formats would reduce payload by 25–35%.",
    severity: "notice",
    isScoring: false,
    basePenalty: 0,
    confidenceType: "confirmed",
    evaluationMode: "deterministic",
    applicableResourceTypes: ["html_page"],
    primaryPageClasses: ["all_html_pages"],
    exclusionFilterDescription: "Applies to PNG/JPEG image assets exceeding 100 KB in transfer size.",
    diagnosticImpact: "Increases mobile data consumption and delays Largest Contentful Paint (LCP).",
  },
  {
    ruleCode: "ASSET_UNMINIFIED_RESOURCE",
    category: "page_speed_assets",
    title: "Unminified internal CSS or JavaScript resource (> 20 KB)",
    description: "Internal stylesheets or script assets are served without minification, containing unnecessary comments and whitespace.",
    severity: "notice",
    isScoring: false,
    basePenalty: 0,
    confidenceType: "confirmed",
    evaluationMode: "deterministic",
    applicableResourceTypes: ["html_page"],
    primaryPageClasses: ["all_html_pages"],
    exclusionFilterDescription: "Excludes third-party CDNs, source maps, and pre-minified assets (.min.js/.min.css).",
    diagnosticImpact: "Increases network payload and parse times for CSSOM and JavaScript execution.",
  },
];

export function getImplementedRulesCount(): number {
  return IMPLEMENTED_DIAGNOSTIC_RULES.length;
}

export function getRuleMetadata(ruleCode: string): DiagnosticRuleMetadata | undefined {
  return IMPLEMENTED_DIAGNOSTIC_RULES.find((r) => r.ruleCode === ruleCode);
}

